from __future__ import annotations

# EXP-1 mirror server -- mrexodia-ida-pro-mcp (mrexodia/ida-pro-mcp).
# GENERATED by scripts/exp1_generate_mirror_server.py from
# evals/fixtures/exp1_mirrors/mrexodia-ida-pro-mcp.json -- do not hand-edit.
#
# LOCAL MIRROR ONLY: real tool names + VERBATIM docstrings from public source.
# Generic stub body (no live APIs, no per-tool logic) -- EXP-1's regime classifier
# tests tool SELECTION only, never call-correctness.
#
# commit=abb2732ad0d759d750c2e38b616f7f3e949ed2f9; extraction_method=ast; doc_density_composite=80.0; params are name-only placeholders (annotation='Any') -- EXP-1 classifier tests selection only, not call-correctness.

import asyncio
import json

import mcp.types as types
from mcp.server import Server
from mcp.server.lowlevel.server import NotificationOptions
from mcp.server.models import InitializationOptions
from mcp.server.stdio import stdio_server

server = Server("exp1_mrexodia_ida_pro_mcp")

DOCSTRINGS: dict[str, str] = {
    "idb_open": "Open a binary, activate it, and warm up subsystems in one call.",
    "idb_list": "List open IDA sessions.",
    "decompile": "Decompile function(s) at address(es); returns pseudocode and per-item errors.",
    "disasm": "Disassemble function with offset/max_instructions pagination and optional total count.",
    "func_profile": "Profile functions with summary metrics and optional sampled details.",
    "analyze_batch": "Run comprehensive analysis over one or more target functions.",
    "xrefs_to": "Return xrefs to address(es) or named symbols, capped per target with truncation flag.",
    "xref_query": "Query xrefs with direction/type filters and pagination.",
    "xrefs_to_field": "Get cross-references to structure fields",
    "callees": "Return unique callees per function, capped by limit.",
    "find_bytes": "Search byte patterns (supports ??) with offset/limit pagination.",
    "basic_blocks": "Return function CFG blocks with offset/max_blocks pagination.",
    "find": "Search strings/immediates/refs for targets with offset/limit pagination.",
    "insn_query": "Query instructions with mnemonic/operand filters and scoped scans.",
    "export_funcs": "Export function data for addresses in json/c_header/prototypes formats.",
    "callgraph": "Build bounded callgraph from roots with depth/node/edge limits.",
    "analyze_function": "Compact single-function analysis: pseudocode, strings, constants, callers, callees, xrefs, blocks.",
    "analyze_component": "Analyze related functions as a group: per-function summaries, internal call graph, shared data.",
    "diff_before_after": "Rename a function, set its type, or add a comment, and immediately see the\nbefore/after decompilation side by side. Use this instead of calling rename\nthen decompile separately when you want to verify that a rename or type change\nactually improved readability. Actions: 'rename_func' (action_args: {name: str}),\n'set_type' (action_args: {type: str}), 'set_comment' (action_args: {comment: str}).\nReturns {before, after, action_applied, changes_detected}. Especially useful\nduring batch renaming to confirm each change had the intended effect.",
    "trace_data_flow": "Follow cross-references from or to an address, automatically traversing\nmultiple hops. Use 'forward' to see where data flows TO (xrefs-from), or\n'backward' to see where data flows FROM (xrefs-to). At each node in the\ntraversal, returns the function name, instruction, and whether it's code or\ndata. Use this when you find an interesting string, constant, or global and\nwant to understand every code path that touches it without manually chaining\nxrefs_to calls. Do not use for call graph traversal — use callgraph for that.\nmax_depth controls how many hops to follow (default 5, max 20).",
    "server_health": "Health/ready probe for MCP server and current IDB state.",
    "lookup_funcs": "Get functions by address or name (auto-detects)",
    "int_convert": "Convert numbers to different formats",
    "list_funcs": "List functions with optional filtering and offset/count pagination.",
    "func_query": "Query functions with richer filtering than list_funcs.",
    "list_globals": "List globals with optional filtering and offset/count pagination.",
    "entity_query": "Query IDB entities with typed filters, projection, and pagination.",
    "imports": "List imports with module names using offset/count pagination.",
    "imports_query": "Query imports with richer filtering than imports(offset,count).",
    "idb_save": "Save active IDB to disk, optionally to a provided path.\n\nIn the GUI (idaq) the open database is backed by loose working files\n(.id0/.id1/.id2/.nam/.til) that IDA actively manages; packing+killing them\nout from under the running GUI corrupts the database on the next reopen\n(issue #446). So in GUI mode this uses IDA's native in-place save\n(equivalent to Ctrl+W / save_database(None, 0)), and for an explicit\ndifferent destination writes a compressed copy WITHOUT killing the live\nworking files.\n\nOnly headless idalib — which has no live loose files to clobber — packs into\na single compressed .i64/.idb, removing the loose working files.",
    "find_regex": "Search strings by case-insensitive regex with offset/limit pagination.",
    "search_text": "Search the rendered listing for `pattern` over [start, end).\n\nIterates `idautils.Heads()` in pure Python and renders each via\n`ida_lines.generate_disassembly()`. Per-head iteration is cheap and\nyields between heads, so the per-tool deadline (sync_wrapper) and the\nUI Cancel button both interrupt the walk reliably — unlike the C-level\n`ida_search.find_text()` it replaced, which on huge .text segments\ncould run for minutes without polling `user_cancelled()`.\n\nUse `start`/`end` to scope the work for predictable performance on\nlarge binaries; without them the scan covers the whole image.",
    "dbg_start": "Start debugger session for current target.\n\nRequires the user to have selected a debugger (Debugger -> Select debugger)\nand configured the target (executable path, arguments, attach process,\nremote host, etc.). If this call fails, do not retry repeatedly. Stop,\nexplain to the user that debugging is not yet configured, and ask them\nto set up the debugger and dismiss any IDA dialogs (e.g. \"matching\nexecutable names\") before trying again.",
    "dbg_status": "Return debugger lifecycle state and current IP if suspended.",
    "dbg_exit": "Terminate active debugger session.",
    "dbg_continue": "Resume execution in active debugger session.",
    "dbg_run_to": "Run debuggee until target address is reached.",
    "dbg_step_into": "Execute one instruction, stepping into calls.",
    "dbg_step_over": "Execute one instruction, stepping over calls.",
    "dbg_bps": "List breakpoints with address, enabled status, condition, and language.",
    "dbg_add_bp": "Add breakpoints at one or more addresses.",
    "dbg_delete_bp": "Delete breakpoints at one or more addresses.",
    "dbg_toggle_bp": "Enable or disable existing breakpoints in batch.",
    "dbg_set_bp_condition": "Set or clear breakpoint conditions in batch.",
    "dbg_regs_all": "Return full register sets for all debugger threads.",
    "dbg_regs_remote": "Return full register sets for specified thread IDs.",
    "dbg_regs": "Return full registers for current debugger thread.",
    "dbg_gpregs_remote": "Get GP registers for threads",
    "dbg_gpregs": "Get current thread GP registers",
    "dbg_regs_named_remote": "Return selected registers for a specific thread ID.",
    "dbg_regs_named": "Get specific current thread registers",
    "dbg_stacktrace": "Return current call stack with module and symbol context.",
    "dbg_read": "Read debuggee memory from one or more regions.",
    "dbg_write": "Write bytes to debuggee memory regions.",
    "get_bytes": "Read bytes from memory addresses",
    "get_int": "Read integer values from memory addresses",
    "get_string": "Read strings from memory addresses",
    "get_global_value": "Read global variable values by address or symbol name.",
    "patch": "Patch bytes at memory addresses with hex data",
    "put_int": "Write integer values to memory addresses",
    "add_bookmark": "Add or replace the IDA bookmark at an address. Set prefix=\"\" for no prefix.",
    "set_comments": "Set comments at addresses (both disassembly and decompiler views)",
    "append_comments": "Append comments at addresses, deduping exact text by default.",
    "patch_asm": "Patch assembly instructions at addresses",
    "rename": "Batch-rename funcs/globals/locals/stack vars with dry-run options.",
    "define_func": "Define functions; IDA infers bounds unless end is provided.",
    "define_code": "Convert bytes to code instruction(s) at address(es).",
    "undefine": "Undefine item(s) at address(es), converting back to raw bytes.",
    "force_recompile": "Invalidate the Hex-Rays decompile cache for one or more functions.\n\nUse after `set_type`, `rename` (especially of locals), `set_op_type`, or\n`make_data` so the next `decompile` call regenerates fresh pseudocode\ninstead of returning a cached, stale view.",
    "set_op_type": "Set the type of an instruction operand. GUI 'Y' / 'O' / '#' equivalent.\n\nTags an operand at a specific instruction with a desired interpretation.\nUseful when the decompiler picks an awkward expression form (e.g., the\n\"earlier-named-symbol + offset\" form for contiguous globals).\n\n`kind` values:\n- `\"stroff\"`: struct-offset reference. Requires `struct`, optional `delta`.\n- `\"offset\"`: absolute offset / pointer. Optional `target_addr`.\n- `\"hex\" | \"dec\" | \"char\" | \"binary\" | \"octal\"`: numeric format.\n- `\"stkvar\"`: stack-variable reference (function-local).",
    "make_data": "Create a typed data symbol at an address, replacing any prior items.\n\nUse this to harden a symbol boundary that the decompiler is currently\nexpressing through a neighboring global plus offset. `set_type` alone\nleaves the underlying byte items unchanged; this tool deletes them\nfirst, then re-creates them at the right size with the right type, then\noptionally renames.\n\nThe `type` field is a full C declaration with a placeholder name, e.g.\n`\"ISP_SNS_STATE_S * g_pastImx290[4]\"` — IDA parses it via SetType.",
    "py_eval": "Execute Python in IDA context and return result/stdout/stderr.",
    "py_exec_file": "Execute a Python script file in IDA context and return stdout/stderr.\n\nUnlike py_eval, this runs the entire file with exec() using a single shared\nglobals dict (no locals split), so top-level definitions are visible to all\ncode in the script. Handles large scripts that would be unwieldy as inline code.",
    "make_signature": "Create unique byte signatures for addresses. Generates the shortest\nunique signature starting at each address by walking instructions and\nwildcarding operands. Useful for finding stable patterns that survive\nrecompilation.",
    "make_signature_for_function": "Create unique byte signatures for function entry points. Resolves each\nname/address to a function, then generates the shortest unique signature\nstarting at the function start.",
    "make_signature_for_range": "Create a byte signature for a specific address range (e.g. a selected\nregion). Unlike make_signature, this does NOT guarantee uniqueness — it\nsimply encodes the bytes in the range with optional operand wildcarding.",
    "find_xref_signatures": "Find signatures for code locations that reference an address. For each\ninput address, finds all code cross-references TO it, generates a unique\nsignature at each xref site, and returns the shortest ones. Ideal for\ncreating signatures for data addresses, vtable entries, or string\nreferences that can't be signatured directly.",
    "stack_frame": "Return stack variables for function address(es).",
    "declare_stack": "Create stack variables from typed stack declarations.",
    "delete_stack": "Delete stack variables by name or offset.",
    "survey_binary": "Get a compact overview of the binary in one call. Returns file metadata,\nsegment layout, entry points, statistics, top 15 strings and functions ranked\nby xref count (functions include classification: thunk/wrapper/leaf/dispatcher/\ncomplex), imports by category, and call graph summary. Use this as your FIRST\ntool call when starting analysis. Do not call list_funcs, imports, or find_regex\nseparately for triage — this returns all of that. Use detail_level='minimal'\nfor binaries with >10k functions.",
    "declare_type": "Declare C type definitions in local type library.",
    "enum_upsert": "Create or extend local enums in an idempotent way.",
    "read_struct": "Read struct fields from memory at address; auto-detect type when possible.",
    "search_structs": "Search local structs/unions by name pattern.",
    "type_query": "Query local types with structured filters/projection-friendly output.",
    "type_inspect": "Inspect named types (size/kind/declaration/members).",
    "set_type": "Apply types (function/global/local/stack)",
    "type_apply_batch": "Apply multiple type edits and return aggregate status.",
    "infer_types": "Infer and apply likely types at target addresses."
}

TOOL_SCHEMAS: dict[str, dict] = {
    "idb_open": {
        "type": "object",
        "properties": {
            "input_path": {
                "type": "string"
            },
            "run_auto_analysis": {
                "type": "string"
            },
            "build_caches": {
                "type": "string"
            },
            "init_hexrays": {
                "type": "string"
            },
            "idle_ttl_sec": {
                "type": "string"
            },
            "preferred_session_id": {
                "type": "string"
            }
        },
        "required": [
            "input_path",
            "run_auto_analysis",
            "build_caches",
            "init_hexrays",
            "idle_ttl_sec",
            "preferred_session_id"
        ]
    },
    "idb_list": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "decompile": {
        "type": "object",
        "properties": {
            "addr": {
                "type": "string"
            },
            "include_addresses": {
                "type": "string"
            }
        },
        "required": [
            "addr",
            "include_addresses"
        ]
    },
    "disasm": {
        "type": "object",
        "properties": {
            "addr": {
                "type": "string"
            },
            "max_instructions": {
                "type": "string"
            },
            "offset": {
                "type": "string"
            },
            "include_total": {
                "type": "string"
            }
        },
        "required": [
            "addr",
            "max_instructions",
            "offset",
            "include_total"
        ]
    },
    "func_profile": {
        "type": "object",
        "properties": {
            "queries": {
                "type": "string"
            }
        },
        "required": [
            "queries"
        ]
    },
    "analyze_batch": {
        "type": "object",
        "properties": {
            "queries": {
                "type": "string"
            }
        },
        "required": [
            "queries"
        ]
    },
    "xrefs_to": {
        "type": "object",
        "properties": {
            "addrs": {
                "type": "string"
            },
            "limit": {
                "type": "string"
            }
        },
        "required": [
            "addrs",
            "limit"
        ]
    },
    "xref_query": {
        "type": "object",
        "properties": {
            "queries": {
                "type": "string"
            }
        },
        "required": [
            "queries"
        ]
    },
    "xrefs_to_field": {
        "type": "object",
        "properties": {
            "queries": {
                "type": "string"
            }
        },
        "required": [
            "queries"
        ]
    },
    "callees": {
        "type": "object",
        "properties": {
            "addrs": {
                "type": "string"
            },
            "limit": {
                "type": "string"
            }
        },
        "required": [
            "addrs",
            "limit"
        ]
    },
    "find_bytes": {
        "type": "object",
        "properties": {
            "patterns": {
                "type": "string"
            },
            "limit": {
                "type": "string"
            },
            "offset": {
                "type": "string"
            }
        },
        "required": [
            "patterns",
            "limit",
            "offset"
        ]
    },
    "basic_blocks": {
        "type": "object",
        "properties": {
            "addrs": {
                "type": "string"
            },
            "max_blocks": {
                "type": "string"
            },
            "offset": {
                "type": "string"
            }
        },
        "required": [
            "addrs",
            "max_blocks",
            "offset"
        ]
    },
    "find": {
        "type": "object",
        "properties": {
            "type": {
                "type": "string"
            },
            "targets": {
                "type": "string"
            },
            "limit": {
                "type": "string"
            },
            "offset": {
                "type": "string"
            }
        },
        "required": [
            "type",
            "targets",
            "limit",
            "offset"
        ]
    },
    "insn_query": {
        "type": "object",
        "properties": {
            "queries": {
                "type": "string"
            }
        },
        "required": [
            "queries"
        ]
    },
    "export_funcs": {
        "type": "object",
        "properties": {
            "addrs": {
                "type": "string"
            },
            "format": {
                "type": "string"
            }
        },
        "required": [
            "addrs",
            "format"
        ]
    },
    "callgraph": {
        "type": "object",
        "properties": {
            "roots": {
                "type": "string"
            },
            "max_depth": {
                "type": "string"
            },
            "max_nodes": {
                "type": "string"
            },
            "max_edges": {
                "type": "string"
            },
            "max_edges_per_func": {
                "type": "string"
            }
        },
        "required": [
            "roots",
            "max_depth",
            "max_nodes",
            "max_edges",
            "max_edges_per_func"
        ]
    },
    "analyze_function": {
        "type": "object",
        "properties": {
            "addr": {
                "type": "string"
            },
            "include_asm": {
                "type": "string"
            }
        },
        "required": [
            "addr",
            "include_asm"
        ]
    },
    "analyze_component": {
        "type": "object",
        "properties": {
            "addrs": {
                "type": "string"
            }
        },
        "required": [
            "addrs"
        ]
    },
    "diff_before_after": {
        "type": "object",
        "properties": {
            "addr": {
                "type": "string"
            },
            "action": {
                "type": "string"
            },
            "action_args": {
                "type": "string"
            }
        },
        "required": [
            "addr",
            "action",
            "action_args"
        ]
    },
    "trace_data_flow": {
        "type": "object",
        "properties": {
            "addr": {
                "type": "string"
            },
            "direction": {
                "type": "string"
            },
            "max_depth": {
                "type": "string"
            }
        },
        "required": [
            "addr",
            "direction",
            "max_depth"
        ]
    },
    "server_health": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "lookup_funcs": {
        "type": "object",
        "properties": {
            "queries": {
                "type": "string"
            }
        },
        "required": [
            "queries"
        ]
    },
    "int_convert": {
        "type": "object",
        "properties": {
            "inputs": {
                "type": "string"
            }
        },
        "required": [
            "inputs"
        ]
    },
    "list_funcs": {
        "type": "object",
        "properties": {
            "queries": {
                "type": "string"
            }
        },
        "required": [
            "queries"
        ]
    },
    "func_query": {
        "type": "object",
        "properties": {
            "queries": {
                "type": "string"
            }
        },
        "required": [
            "queries"
        ]
    },
    "list_globals": {
        "type": "object",
        "properties": {
            "queries": {
                "type": "string"
            }
        },
        "required": [
            "queries"
        ]
    },
    "entity_query": {
        "type": "object",
        "properties": {
            "queries": {
                "type": "string"
            }
        },
        "required": [
            "queries"
        ]
    },
    "imports": {
        "type": "object",
        "properties": {
            "offset": {
                "type": "string"
            },
            "count": {
                "type": "string"
            }
        },
        "required": [
            "offset",
            "count"
        ]
    },
    "imports_query": {
        "type": "object",
        "properties": {
            "queries": {
                "type": "string"
            }
        },
        "required": [
            "queries"
        ]
    },
    "idb_save": {
        "type": "object",
        "properties": {
            "path": {
                "type": "string"
            }
        },
        "required": [
            "path"
        ]
    },
    "find_regex": {
        "type": "object",
        "properties": {
            "pattern": {
                "type": "string"
            },
            "limit": {
                "type": "string"
            },
            "offset": {
                "type": "string"
            }
        },
        "required": [
            "pattern",
            "limit",
            "offset"
        ]
    },
    "search_text": {
        "type": "object",
        "properties": {
            "pattern": {
                "type": "string"
            },
            "limit": {
                "type": "string"
            },
            "start": {
                "type": "string"
            },
            "end": {
                "type": "string"
            },
            "regex": {
                "type": "string"
            },
            "case_sensitive": {
                "type": "string"
            },
            "include": {
                "type": "string"
            },
            "code_only": {
                "type": "string"
            }
        },
        "required": [
            "pattern",
            "limit",
            "start",
            "end",
            "regex",
            "case_sensitive",
            "include",
            "code_only"
        ]
    },
    "dbg_start": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "dbg_status": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "dbg_exit": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "dbg_continue": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "dbg_run_to": {
        "type": "object",
        "properties": {
            "addr": {
                "type": "string"
            }
        },
        "required": [
            "addr"
        ]
    },
    "dbg_step_into": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "dbg_step_over": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "dbg_bps": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "dbg_add_bp": {
        "type": "object",
        "properties": {
            "addrs": {
                "type": "string"
            }
        },
        "required": [
            "addrs"
        ]
    },
    "dbg_delete_bp": {
        "type": "object",
        "properties": {
            "addrs": {
                "type": "string"
            }
        },
        "required": [
            "addrs"
        ]
    },
    "dbg_toggle_bp": {
        "type": "object",
        "properties": {
            "items": {
                "type": "string"
            }
        },
        "required": [
            "items"
        ]
    },
    "dbg_set_bp_condition": {
        "type": "object",
        "properties": {
            "items": {
                "type": "string"
            }
        },
        "required": [
            "items"
        ]
    },
    "dbg_regs_all": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "dbg_regs_remote": {
        "type": "object",
        "properties": {
            "tids": {
                "type": "string"
            }
        },
        "required": [
            "tids"
        ]
    },
    "dbg_regs": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "dbg_gpregs_remote": {
        "type": "object",
        "properties": {
            "tids": {
                "type": "string"
            }
        },
        "required": [
            "tids"
        ]
    },
    "dbg_gpregs": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "dbg_regs_named_remote": {
        "type": "object",
        "properties": {
            "thread_id": {
                "type": "string"
            },
            "register_names": {
                "type": "string"
            }
        },
        "required": [
            "thread_id",
            "register_names"
        ]
    },
    "dbg_regs_named": {
        "type": "object",
        "properties": {
            "register_names": {
                "type": "string"
            }
        },
        "required": [
            "register_names"
        ]
    },
    "dbg_stacktrace": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "dbg_read": {
        "type": "object",
        "properties": {
            "regions": {
                "type": "string"
            }
        },
        "required": [
            "regions"
        ]
    },
    "dbg_write": {
        "type": "object",
        "properties": {
            "regions": {
                "type": "string"
            }
        },
        "required": [
            "regions"
        ]
    },
    "get_bytes": {
        "type": "object",
        "properties": {
            "regions": {
                "type": "string"
            }
        },
        "required": [
            "regions"
        ]
    },
    "get_int": {
        "type": "object",
        "properties": {
            "queries": {
                "type": "string"
            }
        },
        "required": [
            "queries"
        ]
    },
    "get_string": {
        "type": "object",
        "properties": {
            "addrs": {
                "type": "string"
            }
        },
        "required": [
            "addrs"
        ]
    },
    "get_global_value": {
        "type": "object",
        "properties": {
            "queries": {
                "type": "string"
            }
        },
        "required": [
            "queries"
        ]
    },
    "patch": {
        "type": "object",
        "properties": {
            "patches": {
                "type": "string"
            }
        },
        "required": [
            "patches"
        ]
    },
    "put_int": {
        "type": "object",
        "properties": {
            "items": {
                "type": "string"
            }
        },
        "required": [
            "items"
        ]
    },
    "add_bookmark": {
        "type": "object",
        "properties": {
            "addr": {
                "type": "string"
            },
            "name": {
                "type": "string"
            },
            "prefix": {
                "type": "string"
            }
        },
        "required": [
            "addr",
            "name",
            "prefix"
        ]
    },
    "set_comments": {
        "type": "object",
        "properties": {
            "items": {
                "type": "string"
            }
        },
        "required": [
            "items"
        ]
    },
    "append_comments": {
        "type": "object",
        "properties": {
            "items": {
                "type": "string"
            }
        },
        "required": [
            "items"
        ]
    },
    "patch_asm": {
        "type": "object",
        "properties": {
            "items": {
                "type": "string"
            }
        },
        "required": [
            "items"
        ]
    },
    "rename": {
        "type": "object",
        "properties": {
            "batch": {
                "type": "string"
            }
        },
        "required": [
            "batch"
        ]
    },
    "define_func": {
        "type": "object",
        "properties": {
            "items": {
                "type": "string"
            }
        },
        "required": [
            "items"
        ]
    },
    "define_code": {
        "type": "object",
        "properties": {
            "items": {
                "type": "string"
            }
        },
        "required": [
            "items"
        ]
    },
    "undefine": {
        "type": "object",
        "properties": {
            "items": {
                "type": "string"
            }
        },
        "required": [
            "items"
        ]
    },
    "force_recompile": {
        "type": "object",
        "properties": {
            "items": {
                "type": "string"
            }
        },
        "required": [
            "items"
        ]
    },
    "set_op_type": {
        "type": "object",
        "properties": {
            "items": {
                "type": "string"
            }
        },
        "required": [
            "items"
        ]
    },
    "make_data": {
        "type": "object",
        "properties": {
            "items": {
                "type": "string"
            }
        },
        "required": [
            "items"
        ]
    },
    "py_eval": {
        "type": "object",
        "properties": {
            "code": {
                "type": "string"
            }
        },
        "required": [
            "code"
        ]
    },
    "py_exec_file": {
        "type": "object",
        "properties": {
            "file_path": {
                "type": "string"
            }
        },
        "required": [
            "file_path"
        ]
    },
    "make_signature": {
        "type": "object",
        "properties": {
            "addrs": {
                "type": "string"
            },
            "format": {
                "type": "string"
            },
            "wildcard_operands": {
                "type": "string"
            },
            "max_length": {
                "type": "string"
            }
        },
        "required": [
            "addrs",
            "format",
            "wildcard_operands",
            "max_length"
        ]
    },
    "make_signature_for_function": {
        "type": "object",
        "properties": {
            "addrs": {
                "type": "string"
            },
            "format": {
                "type": "string"
            },
            "wildcard_operands": {
                "type": "string"
            },
            "max_length": {
                "type": "string"
            }
        },
        "required": [
            "addrs",
            "format",
            "wildcard_operands",
            "max_length"
        ]
    },
    "make_signature_for_range": {
        "type": "object",
        "properties": {
            "start": {
                "type": "string"
            },
            "end": {
                "type": "string"
            },
            "format": {
                "type": "string"
            },
            "wildcard_operands": {
                "type": "string"
            }
        },
        "required": [
            "start",
            "end",
            "format",
            "wildcard_operands"
        ]
    },
    "find_xref_signatures": {
        "type": "object",
        "properties": {
            "addrs": {
                "type": "string"
            },
            "format": {
                "type": "string"
            },
            "top": {
                "type": "string"
            },
            "max_length": {
                "type": "string"
            }
        },
        "required": [
            "addrs",
            "format",
            "top",
            "max_length"
        ]
    },
    "stack_frame": {
        "type": "object",
        "properties": {
            "addrs": {
                "type": "string"
            }
        },
        "required": [
            "addrs"
        ]
    },
    "declare_stack": {
        "type": "object",
        "properties": {
            "items": {
                "type": "string"
            }
        },
        "required": [
            "items"
        ]
    },
    "delete_stack": {
        "type": "object",
        "properties": {
            "items": {
                "type": "string"
            }
        },
        "required": [
            "items"
        ]
    },
    "survey_binary": {
        "type": "object",
        "properties": {
            "detail_level": {
                "type": "string"
            }
        },
        "required": [
            "detail_level"
        ]
    },
    "declare_type": {
        "type": "object",
        "properties": {
            "decls": {
                "type": "string"
            }
        },
        "required": [
            "decls"
        ]
    },
    "enum_upsert": {
        "type": "object",
        "properties": {
            "queries": {
                "type": "string"
            }
        },
        "required": [
            "queries"
        ]
    },
    "read_struct": {
        "type": "object",
        "properties": {
            "queries": {
                "type": "string"
            }
        },
        "required": [
            "queries"
        ]
    },
    "search_structs": {
        "type": "object",
        "properties": {
            "filter": {
                "type": "string"
            }
        },
        "required": [
            "filter"
        ]
    },
    "type_query": {
        "type": "object",
        "properties": {
            "queries": {
                "type": "string"
            }
        },
        "required": [
            "queries"
        ]
    },
    "type_inspect": {
        "type": "object",
        "properties": {
            "queries": {
                "type": "string"
            }
        },
        "required": [
            "queries"
        ]
    },
    "set_type": {
        "type": "object",
        "properties": {
            "edits": {
                "type": "string"
            }
        },
        "required": [
            "edits"
        ]
    },
    "type_apply_batch": {
        "type": "object",
        "properties": {
            "batch": {
                "type": "string"
            }
        },
        "required": [
            "batch"
        ]
    },
    "infer_types": {
        "type": "object",
        "properties": {
            "addrs": {
                "type": "string"
            }
        },
        "required": [
            "addrs"
        ]
    }
}


@server.list_tools()
async def list_tools() -> list[types.Tool]:
    return [
        types.Tool(name=name, description=DOCSTRINGS[name], inputSchema=TOOL_SCHEMAS[name])
        for name in DOCSTRINGS
    ]


@server.call_tool()
async def call_tool(
    name: str, arguments: dict
) -> list[types.TextContent | types.ImageContent | types.EmbeddedResource]:
    if name not in DOCSTRINGS:
        raise ValueError(f"Unknown tool: {name}")
    return [types.TextContent(type="text", text=json.dumps({"stub": True, "tool": name, "args": arguments}))]


async def main() -> None:
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name="exp1_mrexodia_ida_pro_mcp",
                server_version="0.1.0",
                capabilities=server.get_capabilities(
                    notification_options=NotificationOptions(),
                    experimental_capabilities={},
                ),
            ),
        )


if __name__ == "__main__":
    asyncio.run(main())
