from __future__ import annotations

# EXP-1 mirror server -- lucasastorian-llmwiki (lucasastorian/llmwiki).
# GENERATED by scripts/exp1_generate_mirror_server.py from
# evals/fixtures/exp1_mirrors/lucasastorian-llmwiki.json -- do not hand-edit.
#
# LOCAL MIRROR ONLY: real tool names + VERBATIM docstrings from public source.
# Generic stub body (no live APIs, no per-tool logic) -- EXP-1's regime classifier
# tests tool SELECTION only, never call-correctness.
#
# commit=2f190303f8c978400f422b90ae666262ce5d8dc4; extraction_method=ast; doc_density_composite=80.0; params are name-only placeholders (annotation='Any') -- EXP-1 classifier tests selection only, not call-correctness.

import asyncio
import json

import mcp.types as types
from mcp.server import Server
from mcp.server.lowlevel.server import NotificationOptions
from mcp.server.models import InitializationOptions
from mcp.server.stdio import stdio_server

server = Server("exp1_lucasastorian_llmwiki")

DOCSTRINGS: dict[str, str] = {
    "ping": "Test connectivity",
    "delete": "Delete documents or wiki pages from the knowledge vault.\n\nProvide a path to delete a single file, or a glob pattern to delete multiple.\nExamples:\n- `path=\"old-notes.md\"` — delete a single file\n- `path=\"/wiki/drafts/*\"` — delete all files in a folder\n- `path=\"/wiki/**\"` — delete the entire wiki\n\nNote: overview.md and log.md are structural pages and cannot be deleted.\nReturns a list of deleted files. This action cannot be undone.",
    "guide": "Get started with LLM Wiki. Call this to understand how the knowledge vault works and see your available knowledge bases.",
    "lint": "Run deterministic hygiene checks across a knowledge base.\n\nChecks wiki frontmatter, tag/date index consistency, footnote hygiene, citation resolution, citation graph edges, dangling wiki links, orphan pages, uncited sources, and stale pages.\n\nUse `path` to scope the run, e.g. `*`, `/wiki/**`, or `/wiki/concepts/*.md`.",
    "create_knowledge_base": "Create a new knowledge base and scaffold starter overview/log pages.\n\nSet kind='course' to create a course instead of a wiki — same structure, but the app renders lesson progress (mark-complete, current/locked lessons). Default 'wiki'.\n\nIn hosted mode this creates a separate knowledge base with a unique slug. In local MCP mode there is one workspace per server, so this returns the existing workspace if it has already been initialized.",
    "set_course_mode": "Convert an existing knowledge base into a course (kind='course') or back into a plain wiki (kind='wiki'). A course renders its pages as ordered lessons with progress tracking; a wiki is free-form. Reversible — this only changes how the app renders the knowledge base, never its content.",
    "list_knowledge_bases": "List the user's knowledge bases with their names and slugs.\n\nEvery other tool takes a `knowledge_base` slug — call this first to discover the valid slugs, or whenever you need to confirm which knowledge bases exist.",
    "read": "Read document content from the knowledge vault.\n\nAccepts a single file path OR a glob pattern to batch-read multiple files:\n- `path=\"notes.md\"` — read one file\n- `path=\"*.md\"` — read all markdown files in root\n- `path=\"/wiki/**\"` — read all wiki pages\n- `path=\"**/*.md\"` — read all markdown files everywhere\n\nBatch reads are the PREFERRED way to read multiple documents at once — use them generously.\nGlob reads sample the first few pages from each document (including PDFs) up to a 120k char budget. This gives you a broad overview of an entire folder in one call. Read individual files for full content.\n\nFor PDFs and office docs, use `pages` to read specific page ranges (e.g. '1-50', '3', '10-30').\nYou can read up to 50+ pages in a single call — use wide ranges to avoid unnecessary round trips.\nFor spreadsheets, each sheet is a page (call without pages first to see sheet names).\nSet `include_images=true` to include embedded images (e.g. figures in PDFs, standalone image files). Off by default to save context — enable when you need to see charts, diagrams, or photos.\n\nWhen reading sources to compile wiki pages, note the filename and page ranges for citation.",
    "search": "Browse or search the knowledge vault.\n\nSources (raw documents) live at `/`. Wiki pages (LLM-compiled) live at `/wiki/`.\n\nModes:\n- list: browse files and folders\n- search: keyword search across document content (searches chunks for precise results with page numbers)\n- references: query the citation/link graph for a document\n\nReferences mode examples:\n- `search(mode=\"references\", path=\"/wiki/concepts/scaling.md\")` — what it cites + what links to it\n- `search(mode=\"references\", path=\"paper.pdf\")` — which wiki pages cite this source\n- `search(mode=\"references\", query=\"uncited\")` — sources with no wiki citations\n- `search(mode=\"references\", query=\"stale\")` — pages flagged as potentially stale\n\nUse `path` to scope: `*` for root, `/wiki/**` for wiki only, `*.pdf` for PDFs, etc.\nUse `tags` to filter by document tags.",
    "create": "Create a new wiki page, note, or asset in the knowledge vault.\n\nWiki pages should be created under `/wiki/` and should cite their sources using markdown footnotes (e.g. `[^1]: paper.pdf, p.3`). If markdown wiki content does not include YAML frontmatter, this tool adds it from `title`, `tags`, and `date_str`.\n\nYou can also create SVG diagrams and CSV data files as wiki assets:\n- `create(path=\"/wiki/\", title=\"architecture-diagram.svg\", content=\"<svg>...</svg>\", tags=[\"diagram\"])`\n- `create(path=\"/wiki/\", title=\"data-table.csv\", content=\"col1,col2\\nval1,val2\", tags=[\"data\"])`\nSVGs and other assets can be embedded in wiki pages via `![Architecture](architecture-diagram.svg)`\n\nRejects if the page already exists — use `overwrite=true` to replace, or use the `edit` tool to modify.",
    "edit": "Replace exact text in an existing wiki page or note.\n\nWorks like find-and-replace: provide the exact text to find (`old_text`) and the replacement (`new_text`). The match must be unique — if multiple matches are found, provide more surrounding context to disambiguate.\n\nRead the page first to see its current content before editing.",
    "append": "Append content to the end of an existing wiki page or note.\n\nUseful for adding new sections, log entries, or additional findings to a page without reading and rewriting the entire document."
}

TOOL_SCHEMAS: dict[str, dict] = {
    "ping": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "delete": {
        "type": "object",
        "properties": {
            "knowledge_base": {
                "type": "string"
            },
            "path": {
                "type": "string"
            }
        },
        "required": [
            "knowledge_base",
            "path"
        ]
    },
    "guide": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "lint": {
        "type": "object",
        "properties": {
            "knowledge_base": {
                "type": "string"
            },
            "path": {
                "type": "string"
            },
            "scope": {
                "type": "string"
            },
            "include_graph": {
                "type": "string"
            }
        },
        "required": [
            "knowledge_base",
            "path",
            "scope",
            "include_graph"
        ]
    },
    "create_knowledge_base": {
        "type": "object",
        "properties": {
            "name": {
                "type": "string"
            },
            "description": {
                "type": "string"
            },
            "kind": {
                "type": "string"
            }
        },
        "required": [
            "name",
            "description",
            "kind"
        ]
    },
    "set_course_mode": {
        "type": "object",
        "properties": {
            "knowledge_base": {
                "type": "string"
            },
            "kind": {
                "type": "string"
            }
        },
        "required": [
            "knowledge_base",
            "kind"
        ]
    },
    "list_knowledge_bases": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "read": {
        "type": "object",
        "properties": {
            "knowledge_base": {
                "type": "string"
            },
            "path": {
                "type": "string"
            },
            "pages": {
                "type": "string"
            },
            "sections": {
                "type": "string"
            },
            "include_images": {
                "type": "string"
            }
        },
        "required": [
            "knowledge_base",
            "path",
            "pages",
            "sections",
            "include_images"
        ]
    },
    "search": {
        "type": "object",
        "properties": {
            "knowledge_base": {
                "type": "string"
            },
            "mode": {
                "type": "string"
            },
            "query": {
                "type": "string"
            },
            "path": {
                "type": "string"
            },
            "tags": {
                "type": "string"
            },
            "limit": {
                "type": "string"
            },
            "annotated_only": {
                "type": "string"
            },
            "scope": {
                "type": "string"
            }
        },
        "required": [
            "knowledge_base",
            "mode",
            "query",
            "path",
            "tags",
            "limit",
            "annotated_only",
            "scope"
        ]
    },
    "create": {
        "type": "object",
        "properties": {
            "knowledge_base": {
                "type": "string"
            },
            "title": {
                "type": "string"
            },
            "content": {
                "type": "string"
            },
            "tags": {
                "type": "string"
            },
            "path": {
                "type": "string"
            },
            "date_str": {
                "type": "string"
            },
            "overwrite": {
                "type": "string"
            }
        },
        "required": [
            "knowledge_base",
            "title",
            "content",
            "tags",
            "path",
            "date_str",
            "overwrite"
        ]
    },
    "edit": {
        "type": "object",
        "properties": {
            "knowledge_base": {
                "type": "string"
            },
            "path": {
                "type": "string"
            },
            "old_text": {
                "type": "string"
            },
            "new_text": {
                "type": "string"
            }
        },
        "required": [
            "knowledge_base",
            "path",
            "old_text",
            "new_text"
        ]
    },
    "append": {
        "type": "object",
        "properties": {
            "knowledge_base": {
                "type": "string"
            },
            "path": {
                "type": "string"
            },
            "content": {
                "type": "string"
            }
        },
        "required": [
            "knowledge_base",
            "path",
            "content"
        ]
    }
}


@server.list_tools()
async def list_tools() -> list[types.Tool]:
    return [
        types.Tool(name=name, description=DOCSTRINGS[name], inputSchema=TOOL_SCHEMAS[name])
        for name in DOCSTRINGS
    ]


@server.call_tool()
async def call_tool(
    name: str, arguments: dict
) -> list[types.TextContent | types.ImageContent | types.EmbeddedResource]:
    if name not in DOCSTRINGS:
        raise ValueError(f"Unknown tool: {name}")
    return [types.TextContent(type="text", text=json.dumps({"stub": True, "tool": name, "args": arguments}))]


async def main() -> None:
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name="exp1_lucasastorian_llmwiki",
                server_version="0.1.0",
                capabilities=server.get_capabilities(
                    notification_options=NotificationOptions(),
                    experimental_capabilities={},
                ),
            ),
        )


if __name__ == "__main__":
    asyncio.run(main())
