from __future__ import annotations

# EXP-1 mirror server -- AminForou-mcp-gsc (AminForou/mcp-gsc).
# GENERATED by scripts/exp1_generate_mirror_server.py from
# evals/fixtures/exp1_mirrors/AminForou-mcp-gsc.json -- do not hand-edit.
#
# LOCAL MIRROR ONLY: real tool names + VERBATIM docstrings from public source.
# Generic stub body (no live APIs, no per-tool logic) -- EXP-1's regime classifier
# tests tool SELECTION only, never call-correctness.
#
# commit=daab327277e28f8efcc83d9964fb1466a91a1d68; extraction_method=ast; doc_density_composite=100.0; params are name-only placeholders (annotation='Any') -- EXP-1 classifier tests selection only, not call-correctness.

import asyncio
import json

import mcp.types as types
from mcp.server import Server
from mcp.server.lowlevel.server import NotificationOptions
from mcp.server.models import InitializationOptions
from mcp.server.stdio import stdio_server

server = Server("exp1_AminForou_mcp_gsc")

DOCSTRINGS: dict[str, str] = {
    "get_capabilities": "Get a full list of all available tools, current auth status, and how to get started.\nALWAYS call this first when asked what tools are available, what this server can do,\nor how to get started. Returns all tool names grouped by category in a single call —\nfaster than searching individually. Also shows if authentication is needed.",
    "list_properties": "List all Google Search Console (GSC) properties and sites the user has access to.\nUse this to see all verified sites, domain properties, and URL-prefix properties\nin the connected Google Search Console account. Always call this first to get the\nexact site_url needed for other tools.",
    "add_site": "Add a site to your Search Console properties.\n\nArgs:\n    site_url: The URL of the site to add (must be exact match e.g. https://example.com, or https://www.example.com, or https://subdomain.example.com/path/, for domain properties use format: sc-domain:example.com)",
    "delete_site": "Remove a site from your Search Console properties.\n\nArgs:\n    site_url: The URL of the site to remove (must be exact match e.g. https://example.com, or https://www.example.com, or https://subdomain.example.com/path/, for domain properties use format: sc-domain:example.com)",
    "get_search_analytics": "Get search analytics data for a specific property.\n\nArgs:\n    site_url: Exact GSC property URL from list_properties (e.g. \"https://example.com/\" or\n              \"sc-domain:example.com\"). Domain properties cover all subdomains — use the\n              domain property as site_url and filter by page to analyze a specific subdomain.\n    days: Number of days to look back (default: 28)\n    dimensions: Dimensions to group by (default: query). Options: query, page, device, country, date\n               You can provide multiple dimensions separated by comma (e.g., \"query,page\")\n    row_limit: Number of rows to return (default: 20, max: 500). Use 5-20 for quick overviews,\n               50-200 for deeper analysis, up to 500 for comprehensive reports. For bulk exports\n               beyond 500 rows, use get_advanced_search_analytics which supports pagination.",
    "get_site_details": "Get detailed information about a specific Search Console property.\n\nArgs:\n    site_url: Exact GSC property URL from list_properties (e.g. \"https://example.com/\" or\n              \"sc-domain:example.com\"). Domain properties cover all subdomains — use the\n              domain property as site_url and filter by page to analyze a specific subdomain.",
    "get_sitemaps": "List all sitemaps for a specific Search Console property.\n\nArgs:\n    site_url: Exact GSC property URL from list_properties (e.g. \"https://example.com/\" or\n              \"sc-domain:example.com\"). Domain properties cover all subdomains — use the\n              domain property as site_url and filter by page to analyze a specific subdomain.",
    "inspect_url_enhanced": "Enhanced URL inspection to check indexing status and rich results in Google.\n\nArgs:\n    site_url: Exact GSC property URL from list_properties (e.g. \"https://example.com/\" or\n              \"sc-domain:example.com\"). Domain properties cover all subdomains — use the\n              domain property as site_url and filter by page to analyze a specific subdomain.\n    page_url: The specific URL to inspect",
    "batch_url_inspection": "Inspect multiple URLs in batch (within API limits).\n\nArgs:\n    site_url: Exact GSC property URL from list_properties (e.g. \"https://example.com/\" or\n              \"sc-domain:example.com\"). Domain properties cover all subdomains — use the\n              domain property as site_url and filter by page to analyze a specific subdomain.\n    urls: List of URLs to inspect, one per line",
    "check_indexing_issues": "Check for specific indexing issues across multiple URLs.\n\nArgs:\n    site_url: Exact GSC property URL from list_properties (e.g. \"https://example.com/\" or\n              \"sc-domain:example.com\"). Domain properties cover all subdomains — use the\n              domain property as site_url and filter by page to analyze a specific subdomain.\n    urls: List of URLs to check, one per line",
    "get_performance_overview": "Get a performance overview for a specific property.\n\nArgs:\n    site_url: Exact GSC property URL from list_properties (e.g. \"https://example.com/\" or\n              \"sc-domain:example.com\"). Domain properties cover all subdomains — use the\n              domain property as site_url and filter by page to analyze a specific subdomain.\n    days: Number of days to look back (default: 28)",
    "get_advanced_search_analytics": "Get advanced search analytics data with sorting, filtering, and pagination.\n\nArgs:\n    site_url: Exact GSC property URL from list_properties (e.g. \"https://example.com/\" or\n              \"sc-domain:example.com\"). Domain properties cover all subdomains — use the\n              domain property as site_url and filter by page to analyze a specific subdomain.\n    start_date: Start date in YYYY-MM-DD format (defaults to 28 days ago)\n    end_date: End date in YYYY-MM-DD format (defaults to today)\n    dimensions: Dimensions to group by, comma-separated (e.g., \"query,page,device\")\n    search_type: Type of search results (WEB, IMAGE, VIDEO, NEWS, DISCOVER)\n    row_limit: Maximum number of rows to return (max 25000)\n    start_row: Starting row for pagination\n    sort_by: Metric to sort by (clicks, impressions, ctr, position)\n    sort_direction: Sort direction (ascending or descending)\n    filter_dimension: Single filter dimension (query, page, country, device). Use 'filters' instead for multiple filters.\n    filter_operator: Single filter operator (contains, equals, notContains, notEquals)\n    filter_expression: Single filter expression value\n    filters: JSON array of filter objects for AND logic across multiple dimensions. Overrides\n             filter_dimension/filter_operator/filter_expression when provided. Each object must\n             have 'dimension', 'operator', and 'expression' keys. Valid dimensions: query, page,\n             country, device. Valid operators: contains, equals, notContains, notEquals.\n             Example: [{\"dimension\":\"country\",\"operator\":\"equals\",\"expression\":\"usa\"},\n                       {\"dimension\":\"device\",\"operator\":\"equals\",\"expression\":\"MOBILE\"}]\n    data_state: Data freshness — \"all\" (default, matches GSC dashboard) or \"final\" (confirmed data only, 2-3 day lag)",
    "compare_search_periods": "Compare search analytics data between two time periods.\n\nArgs:\n    site_url: Exact GSC property URL from list_properties (e.g. \"https://example.com/\" or\n              \"sc-domain:example.com\"). Domain properties cover all subdomains — use the\n              domain property as site_url and filter by page to analyze a specific subdomain.\n    period1_start: Start date for period 1 (YYYY-MM-DD)\n    period1_end: End date for period 1 (YYYY-MM-DD)\n    period2_start: Start date for period 2 (YYYY-MM-DD)\n    period2_end: End date for period 2 (YYYY-MM-DD)\n    dimensions: Dimensions to group by (default: query)\n    limit: Number of top results to compare (default: 10)",
    "get_search_by_page_query": "Get search analytics data for a specific page, broken down by query.\n\nArgs:\n    site_url: Exact GSC property URL from list_properties (e.g. \"https://example.com/\" or\n              \"sc-domain:example.com\"). Domain properties cover all subdomains — use the\n              domain property as site_url and filter by page to analyze a specific subdomain.\n    page_url: The specific page URL to analyze\n    days: Number of days to look back (default: 28)\n    row_limit: Number of rows to return (default: 20, max: 500). Use 5-20 for quick overviews,\n               50-200 for deeper analysis, up to 500 for comprehensive reports. For bulk exports\n               beyond 500 rows, use get_advanced_search_analytics which supports pagination.",
    "list_sitemaps_enhanced": "List all sitemaps for a specific Search Console property with detailed information.\n\nArgs:\n    site_url: Exact GSC property URL from list_properties (e.g. \"https://example.com/\" or\n              \"sc-domain:example.com\"). Domain properties cover all subdomains — use the\n              domain property as site_url and filter by page to analyze a specific subdomain.\n    sitemap_index: Optional sitemap index URL to list child sitemaps",
    "get_sitemap_details": "Get detailed information about a specific sitemap.\n\nArgs:\n    site_url: Exact GSC property URL from list_properties (e.g. \"https://example.com/\" or\n              \"sc-domain:example.com\"). Domain properties cover all subdomains — use the\n              domain property as site_url and filter by page to analyze a specific subdomain.\n    sitemap_url: The full URL of the sitemap to inspect",
    "submit_sitemap": "Submit a new sitemap or resubmit an existing one to Google.\n\nArgs:\n    site_url: Exact GSC property URL from list_properties (e.g. \"https://example.com/\" or\n              \"sc-domain:example.com\"). Domain properties cover all subdomains — use the\n              domain property as site_url and filter by page to analyze a specific subdomain.\n    sitemap_url: The full URL of the sitemap to submit",
    "delete_sitemap": "Delete (unsubmit) a sitemap from Google Search Console.\n\nArgs:\n    site_url: Exact GSC property URL from list_properties (e.g. \"https://example.com/\" or\n              \"sc-domain:example.com\"). Domain properties cover all subdomains — use the\n              domain property as site_url and filter by page to analyze a specific subdomain.\n    sitemap_url: The full URL of the sitemap to delete",
    "manage_sitemaps": "All-in-one tool to manage sitemaps (list, get details, submit, delete).\n\nArgs:\n    site_url: Exact GSC property URL from list_properties (e.g. \"https://example.com/\" or\n              \"sc-domain:example.com\"). Domain properties cover all subdomains — use the\n              domain property as site_url and filter by page to analyze a specific subdomain.\n    action: The action to perform (list, details, submit, delete)\n    sitemap_url: The full URL of the sitemap (required for details, submit, delete)\n    sitemap_index: Optional sitemap index URL for listing child sitemaps (only used with 'list' action)",
    "get_creator_info": "Provides information about Amin Foroutan, the creator of the MCP-GSC tool.",
    "reauthenticate": "Perform a logout and new login sequence.\nDeletes the current OAuth token file and triggers the browser authentication flow.\nUseful when you need to switch to a different Google account."
}

TOOL_SCHEMAS: dict[str, dict] = {
    "get_capabilities": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "list_properties": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "add_site": {
        "type": "object",
        "properties": {
            "site_url": {
                "type": "string"
            }
        },
        "required": [
            "site_url"
        ]
    },
    "delete_site": {
        "type": "object",
        "properties": {
            "site_url": {
                "type": "string"
            }
        },
        "required": [
            "site_url"
        ]
    },
    "get_search_analytics": {
        "type": "object",
        "properties": {
            "site_url": {
                "type": "string"
            },
            "days": {
                "type": "string"
            },
            "dimensions": {
                "type": "string"
            },
            "row_limit": {
                "type": "string"
            }
        },
        "required": [
            "site_url",
            "days",
            "dimensions",
            "row_limit"
        ]
    },
    "get_site_details": {
        "type": "object",
        "properties": {
            "site_url": {
                "type": "string"
            }
        },
        "required": [
            "site_url"
        ]
    },
    "get_sitemaps": {
        "type": "object",
        "properties": {
            "site_url": {
                "type": "string"
            }
        },
        "required": [
            "site_url"
        ]
    },
    "inspect_url_enhanced": {
        "type": "object",
        "properties": {
            "site_url": {
                "type": "string"
            },
            "page_url": {
                "type": "string"
            }
        },
        "required": [
            "site_url",
            "page_url"
        ]
    },
    "batch_url_inspection": {
        "type": "object",
        "properties": {
            "site_url": {
                "type": "string"
            },
            "urls": {
                "type": "string"
            }
        },
        "required": [
            "site_url",
            "urls"
        ]
    },
    "check_indexing_issues": {
        "type": "object",
        "properties": {
            "site_url": {
                "type": "string"
            },
            "urls": {
                "type": "string"
            }
        },
        "required": [
            "site_url",
            "urls"
        ]
    },
    "get_performance_overview": {
        "type": "object",
        "properties": {
            "site_url": {
                "type": "string"
            },
            "days": {
                "type": "string"
            }
        },
        "required": [
            "site_url",
            "days"
        ]
    },
    "get_advanced_search_analytics": {
        "type": "object",
        "properties": {
            "site_url": {
                "type": "string"
            },
            "start_date": {
                "type": "string"
            },
            "end_date": {
                "type": "string"
            },
            "dimensions": {
                "type": "string"
            },
            "search_type": {
                "type": "string"
            },
            "row_limit": {
                "type": "string"
            },
            "start_row": {
                "type": "string"
            },
            "sort_by": {
                "type": "string"
            },
            "sort_direction": {
                "type": "string"
            },
            "filter_dimension": {
                "type": "string"
            },
            "filter_operator": {
                "type": "string"
            },
            "filter_expression": {
                "type": "string"
            },
            "filters": {
                "type": "string"
            },
            "data_state": {
                "type": "string"
            }
        },
        "required": [
            "site_url",
            "start_date",
            "end_date",
            "dimensions",
            "search_type",
            "row_limit",
            "start_row",
            "sort_by",
            "sort_direction",
            "filter_dimension",
            "filter_operator",
            "filter_expression",
            "filters",
            "data_state"
        ]
    },
    "compare_search_periods": {
        "type": "object",
        "properties": {
            "site_url": {
                "type": "string"
            },
            "period1_start": {
                "type": "string"
            },
            "period1_end": {
                "type": "string"
            },
            "period2_start": {
                "type": "string"
            },
            "period2_end": {
                "type": "string"
            },
            "dimensions": {
                "type": "string"
            },
            "limit": {
                "type": "string"
            }
        },
        "required": [
            "site_url",
            "period1_start",
            "period1_end",
            "period2_start",
            "period2_end",
            "dimensions",
            "limit"
        ]
    },
    "get_search_by_page_query": {
        "type": "object",
        "properties": {
            "site_url": {
                "type": "string"
            },
            "page_url": {
                "type": "string"
            },
            "days": {
                "type": "string"
            },
            "row_limit": {
                "type": "string"
            }
        },
        "required": [
            "site_url",
            "page_url",
            "days",
            "row_limit"
        ]
    },
    "list_sitemaps_enhanced": {
        "type": "object",
        "properties": {
            "site_url": {
                "type": "string"
            },
            "sitemap_index": {
                "type": "string"
            }
        },
        "required": [
            "site_url",
            "sitemap_index"
        ]
    },
    "get_sitemap_details": {
        "type": "object",
        "properties": {
            "site_url": {
                "type": "string"
            },
            "sitemap_url": {
                "type": "string"
            }
        },
        "required": [
            "site_url",
            "sitemap_url"
        ]
    },
    "submit_sitemap": {
        "type": "object",
        "properties": {
            "site_url": {
                "type": "string"
            },
            "sitemap_url": {
                "type": "string"
            }
        },
        "required": [
            "site_url",
            "sitemap_url"
        ]
    },
    "delete_sitemap": {
        "type": "object",
        "properties": {
            "site_url": {
                "type": "string"
            },
            "sitemap_url": {
                "type": "string"
            }
        },
        "required": [
            "site_url",
            "sitemap_url"
        ]
    },
    "manage_sitemaps": {
        "type": "object",
        "properties": {
            "site_url": {
                "type": "string"
            },
            "action": {
                "type": "string"
            },
            "sitemap_url": {
                "type": "string"
            },
            "sitemap_index": {
                "type": "string"
            }
        },
        "required": [
            "site_url",
            "action",
            "sitemap_url",
            "sitemap_index"
        ]
    },
    "get_creator_info": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "reauthenticate": {
        "type": "object",
        "properties": {},
        "required": []
    }
}


@server.list_tools()
async def list_tools() -> list[types.Tool]:
    return [
        types.Tool(name=name, description=DOCSTRINGS[name], inputSchema=TOOL_SCHEMAS[name])
        for name in DOCSTRINGS
    ]


@server.call_tool()
async def call_tool(
    name: str, arguments: dict
) -> list[types.TextContent | types.ImageContent | types.EmbeddedResource]:
    if name not in DOCSTRINGS:
        raise ValueError(f"Unknown tool: {name}")
    return [types.TextContent(type="text", text=json.dumps({"stub": True, "tool": name, "args": arguments}))]


async def main() -> None:
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name="exp1_AminForou_mcp_gsc",
                server_version="0.1.0",
                capabilities=server.get_capabilities(
                    notification_options=NotificationOptions(),
                    experimental_capabilities={},
                ),
            ),
        )


if __name__ == "__main__":
    asyncio.run(main())
