from __future__ import annotations

# EXP-1 mirror server -- datalayer-jupyter-mcp-server (datalayer/jupyter-mcp-server).
# GENERATED by scripts/exp1_generate_mirror_server.py from
# evals/fixtures/exp1_mirrors/datalayer-jupyter-mcp-server.json -- do not hand-edit.
#
# LOCAL MIRROR ONLY: real tool names + VERBATIM docstrings from public source.
# Generic stub body (no live APIs, no per-tool logic) -- EXP-1's regime classifier
# tests tool SELECTION only, never call-correctness.
#
# commit=27b91e551d8bbca2da32c334f9f13267290ff815; extraction_method=ast; doc_density_composite=80.0; params are name-only placeholders (annotation='Any') -- EXP-1 classifier tests selection only, not call-correctness.

import asyncio
import json

import mcp.types as types
from mcp.server import Server
from mcp.server.lowlevel.server import NotificationOptions
from mcp.server.models import InitializationOptions
from mcp.server.stdio import stdio_server

server = Server("exp1_datalayer_jupyter_mcp_server")

DOCSTRINGS: dict[str, str] = {
    "list_files": "List all files and directories recursively in the Jupyter server's file system.\nUsed to explore the file system structure of the Jupyter server or to find specific files or directories.",
    "list_kernels": "List all available kernels in the Jupyter server.\n\nThis tool shows all running and available kernel sessions on the Jupyter server,\nincluding their IDs, names, states, connection information, and kernel specifications.\nUseful for monitoring kernel resources and identifying specific kernels for connection.",
    "use_notebook": "Use a notebook and activate it for following cell operations.\nAll cell operations will be performed on the currently activated notebook.\nActivate new notebook will deactivate the previously activated notebook.\nReactivate previously activated notebook using same notebook_name and notebook_path.",
    "list_notebooks": "Enumerate the names of MULTIPLE notebooks that have been used; does not show any notebook's content.",
    "restart_notebook": "Restart the kernel for a specific notebook.",
    "unuse_notebook": "Unuse from a specific notebook and release its resources.",
    "read_notebook": "Read the full cell-by-cell content and structure of ONE specific notebook you already have open.",
    "insert_cell": "Insert a cell to specified position from the currently activated notebook.",
    "overwrite_cell_source": "Replace the entire source of a cell in the currently activated notebook.\nReturns a diff showing the changes made.\n\nUse this when rewriting a cell completely. For small, targeted changes,\nprefer edit_cell_source instead — it is safer for partial edits.",
    "edit_cell_source": "Perform a surgical find-and-replace within a cell's source (like an editor's Edit tool).\nFinds `old_string` in the cell and replaces it with `new_string`. Matching is literal\n(not regex) and may span multiple lines. By default, `old_string` must appear exactly once;\nset `replace_all=True` for multiple occurrences. Returns a diff of the changes made.\n\nPrefer this over overwrite_cell_source for small, targeted edits — it is safer because\nunchanged parts of the cell are left untouched. Use read_cell first to see the current\nsource and construct an accurate old_string.",
    "execute_cell": "Execute a cell from the currently activated notebook with timeout and return it's outputs",
    "insert_execute_code_cell": "Insert a cell at specified index from the currently activated notebook and then execute it with timeout and return it's outputs\nIt is a shortcut tool for insert_cell and execute_cell tools, recommended to use if you want to insert a cell and execute it at the same time",
    "read_cell": "Read a specific cell from the currently activated notebook and return it's metadata (index, type, execution count), source and outputs (for code cells)",
    "delete_cell": "Delete specific cells from the currently activated notebook and return the cell source of deleted cells (if include_source=True).",
    "move_cell": "Move a cell from source_index to target_index within the currently activated notebook.\n\nThe cell is removed from source_index and placed at target_index. Cells in between shift\nto fill the gap. The cell's type, source, and outputs are preserved.\nExample: in a notebook [A, B, C, D], move_cell(1, 3) produces [A, C, D, B].\n\nUse this tool instead of manually deleting and re-inserting a cell — it is atomic and\npreserves cell metadata. Use read_notebook first to see cell indices if needed.",
    "execute_code": "Execute code directly in a kernel (not saved to notebook).\n\nTargets the current activated notebook's kernel by default. Pass kernel_id\nto execute in a specific kernel directly — including raw kernels with no\nnotebook attached.\n\nRecommended to use in following cases:\n1. Execute Jupyter magic commands(e.g., `%timeit`, `%pip install xxx`)\n2. Performance profiling and debugging.\n3. View intermediate variable values(e.g., `print(xxx)`, `df.head()`)\n4. Temporary calculations and quick tests(e.g., `np.mean(df['xxx'])`)\n5. Execute Shell commands in Jupyter server(e.g., `!git xxx`)\n\nUnder no circumstances should you use this tool to:\n1. Import new modules or perform variable assignments that affect subsequent Notebook execution\n2. Execute dangerous code that may harm the Jupyter server or the user's data without permission",
    "connect_to_jupyter": "Connect to a Jupyter server dynamically with URL and token.\n\nThis tool allows you to connect to different Jupyter servers without needing to \nrestart the MCP server or modify configuration files. Particularly useful when:\n- Working with multiple Jupyter servers with different ports/tokens\n- Jupyter server token changes dynamically\n- Need to switch between different Jupyter instances\n\nExample usage:\n- \"Connect to http://localhost:8888 with token abc123\"\n- \"Connect to http://localhost:8889 without authentication\""
}

TOOL_SCHEMAS: dict[str, dict] = {
    "list_files": {
        "type": "object",
        "properties": {
            "path": {
                "type": "string"
            },
            "max_depth": {
                "type": "string"
            },
            "start_index": {
                "type": "string"
            },
            "limit": {
                "type": "string"
            },
            "pattern": {
                "type": "string"
            }
        },
        "required": [
            "path",
            "max_depth",
            "start_index",
            "limit",
            "pattern"
        ]
    },
    "list_kernels": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "use_notebook": {
        "type": "object",
        "properties": {
            "notebook_name": {
                "type": "string"
            },
            "notebook_path": {
                "type": "string"
            },
            "mode": {
                "type": "string"
            },
            "kernel_id": {
                "type": "string"
            }
        },
        "required": [
            "notebook_name",
            "notebook_path",
            "mode",
            "kernel_id"
        ]
    },
    "list_notebooks": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "restart_notebook": {
        "type": "object",
        "properties": {
            "notebook_name": {
                "type": "string"
            }
        },
        "required": [
            "notebook_name"
        ]
    },
    "unuse_notebook": {
        "type": "object",
        "properties": {
            "notebook_name": {
                "type": "string"
            }
        },
        "required": [
            "notebook_name"
        ]
    },
    "read_notebook": {
        "type": "object",
        "properties": {
            "notebook_name": {
                "type": "string"
            },
            "response_format": {
                "type": "string"
            },
            "start_index": {
                "type": "string"
            },
            "limit": {
                "type": "string"
            }
        },
        "required": [
            "notebook_name",
            "response_format",
            "start_index",
            "limit"
        ]
    },
    "insert_cell": {
        "type": "object",
        "properties": {
            "cell_index": {
                "type": "string"
            },
            "cell_type": {
                "type": "string"
            },
            "cell_source": {
                "type": "string"
            }
        },
        "required": [
            "cell_index",
            "cell_type",
            "cell_source"
        ]
    },
    "overwrite_cell_source": {
        "type": "object",
        "properties": {
            "cell_index": {
                "type": "string"
            },
            "cell_source": {
                "type": "string"
            }
        },
        "required": [
            "cell_index",
            "cell_source"
        ]
    },
    "edit_cell_source": {
        "type": "object",
        "properties": {
            "cell_index": {
                "type": "string"
            },
            "old_string": {
                "type": "string"
            },
            "new_string": {
                "type": "string"
            },
            "replace_all": {
                "type": "string"
            }
        },
        "required": [
            "cell_index",
            "old_string",
            "new_string",
            "replace_all"
        ]
    },
    "execute_cell": {
        "type": "object",
        "properties": {
            "cell_index": {
                "type": "string"
            },
            "timeout": {
                "type": "string"
            },
            "stream": {
                "type": "string"
            },
            "progress_interval": {
                "type": "string"
            }
        },
        "required": [
            "cell_index",
            "timeout",
            "stream",
            "progress_interval"
        ]
    },
    "insert_execute_code_cell": {
        "type": "object",
        "properties": {
            "cell_index": {
                "type": "string"
            },
            "cell_source": {
                "type": "string"
            },
            "timeout": {
                "type": "string"
            }
        },
        "required": [
            "cell_index",
            "cell_source",
            "timeout"
        ]
    },
    "read_cell": {
        "type": "object",
        "properties": {
            "cell_index": {
                "type": "string"
            },
            "include_outputs": {
                "type": "string"
            }
        },
        "required": [
            "cell_index",
            "include_outputs"
        ]
    },
    "delete_cell": {
        "type": "object",
        "properties": {
            "cell_indices": {
                "type": "string"
            },
            "include_source": {
                "type": "string"
            }
        },
        "required": [
            "cell_indices",
            "include_source"
        ]
    },
    "move_cell": {
        "type": "object",
        "properties": {
            "source_index": {
                "type": "string"
            },
            "target_index": {
                "type": "string"
            }
        },
        "required": [
            "source_index",
            "target_index"
        ]
    },
    "execute_code": {
        "type": "object",
        "properties": {
            "code": {
                "type": "string"
            },
            "timeout": {
                "type": "string"
            },
            "kernel_id": {
                "type": "string"
            }
        },
        "required": [
            "code",
            "timeout",
            "kernel_id"
        ]
    },
    "connect_to_jupyter": {
        "type": "object",
        "properties": {
            "jupyter_url": {
                "type": "string"
            },
            "jupyter_token": {
                "type": "string"
            },
            "provider": {
                "type": "string"
            }
        },
        "required": [
            "jupyter_url",
            "jupyter_token",
            "provider"
        ]
    }
}


@server.list_tools()
async def list_tools() -> list[types.Tool]:
    return [
        types.Tool(name=name, description=DOCSTRINGS[name], inputSchema=TOOL_SCHEMAS[name])
        for name in DOCSTRINGS
    ]


@server.call_tool()
async def call_tool(
    name: str, arguments: dict
) -> list[types.TextContent | types.ImageContent | types.EmbeddedResource]:
    if name not in DOCSTRINGS:
        raise ValueError(f"Unknown tool: {name}")
    return [types.TextContent(type="text", text=json.dumps({"stub": True, "tool": name, "args": arguments}))]


async def main() -> None:
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name="exp1_datalayer_jupyter_mcp_server",
                server_version="0.1.0",
                capabilities=server.get_capabilities(
                    notification_options=NotificationOptions(),
                    experimental_capabilities={},
                ),
            ),
        )


if __name__ == "__main__":
    asyncio.run(main())
