from __future__ import annotations

# EXP-1 mirror server -- stefanoamorelli-sec-edgar-mcp (stefanoamorelli/sec-edgar-mcp).
# GENERATED by scripts/exp1_generate_mirror_server.py from
# evals/fixtures/exp1_mirrors/stefanoamorelli-sec-edgar-mcp.json -- do not hand-edit.
#
# LOCAL MIRROR ONLY: real tool names + VERBATIM docstrings from public source.
# Generic stub body (no live APIs, no per-tool logic) -- EXP-1's regime classifier
# tests tool SELECTION only, never call-correctness.
#
# commit=c9726addaecec76f8a225f54e77d4ab955f8ddfb; extraction_method=ast; doc_density_composite=80.1; params are name-only placeholders (annotation='Any') -- EXP-1 classifier tests selection only, not call-correctness.

import asyncio
import json

import mcp.types as types
from mcp.server import Server
from mcp.server.lowlevel.server import NotificationOptions
from mcp.server.models import InitializationOptions
from mcp.server.stdio import stdio_server

server = Server("exp1_stefanoamorelli_sec_edgar_mcp")

DOCSTRINGS: dict[str, str] = {
    "analyze_8k": "Analyze an 8-K current report for material events.\n\nArgs:\n    identifier: Company ticker symbol or CIK number\n    accession_number: The 8-K filing accession number\n\nReturns:\n    Analysis of reported items:\n    <items>\n      <item code=\"1.01\">Material agreements</item>\n      <item code=\"2.02\">Results of operations (earnings)</item>\n      <item code=\"5.02\">Officer/director changes</item>\n      <item code=\"7.01\">Regulation FD disclosures</item>\n      <item code=\"8.01\">Other material events</item>\n    </items>",
    "analyze_form4_transactions": "",
    "analyze_insider_sentiment": "Analyze insider trading patterns and frequency.\n\nArgs:\n    identifier: Company ticker symbol or CIK number\n    months: Number of months to analyze (default: 6)\n\nReturns:\n    Filing frequency analysis (high/moderate/low) and recent activity summary.\n\n<note>This provides frequency analysis only. For buy/sell sentiment,\nuse analyze_form4_transactions to examine actual transaction details.</note>",
    "compare_periods": "",
    "discover_company_metrics": "Discover what financial metrics are available for a company.\n\n<tip>Use this tool to find available XBRL concepts before using get_key_metrics.</tip>\n\nArgs:\n    identifier: Company ticker symbol or CIK number\n    search_term: Filter metrics by name (optional)\n\nReturns:\n    List of available XBRL concepts with data counts.",
    "discover_xbrl_concepts": "Discover all XBRL concepts available in a filing.\n\n<tip>Use this to explore available data before extracting specific concepts.</tip>\n\nArgs:\n    identifier: Company ticker symbol or CIK number\n    accession_number: Specific filing accession number (optional)\n    form_type: Form type if no accession number provided (default: \"10-K\")\n    namespace_filter: Filter by namespace (e.g., \"us-gaap\")\n\nReturns:\n    All discovered concepts, namespaces, and sample values.",
    "get_cik_by_ticker": "Convert a stock ticker symbol to its SEC CIK (Central Index Key).\n\nArgs:\n    ticker: Stock ticker symbol (e.g., \"AAPL\", \"NVDA\", \"MSFT\")\n\nReturns:\n    CIK number for use with other SEC EDGAR tools.",
    "get_company_facts": "",
    "get_company_info": "Retrieve company information from SEC records.\n\nArgs:\n    identifier: Company ticker symbol or CIK number\n\nReturns:\n    Company details including name, CIK, SIC code, exchange, and fiscal year end.",
    "get_filing_content": "Get the content of a specific SEC filing with paging support.\n\nArgs:\n    identifier: Company ticker symbol or CIK number\n    accession_number: The accession number of the filing\n    offset: Character offset into the filing content (default: 0)\n    max_chars: Maximum number of characters to return (default: 50000)\n\nReturns:\n    Dictionary containing filing content page and pagination metadata",
    "get_filing_sections": "Extract specific sections from 10-K or 10-Q filings.\n\nArgs:\n    identifier: Company ticker symbol or CIK number\n    accession_number: Filing accession number\n    form_type: Form type (\"10-K\" or \"10-Q\")\n\nReturns:\n    Extracted sections including business description, risk factors, and MD&A.",
    "get_financials": "",
    "get_form4_details": "",
    "get_insider_summary": "Get a summary of insider trading activity.\n\nArgs:\n    identifier: Company ticker symbol or CIK number\n    days: Number of days to analyze (default: 180)\n\nReturns:\n    Summary with filing counts by form type, unique insiders, and recent activity.",
    "get_insider_transactions": "",
    "get_key_metrics": "",
    "get_recent_filings": "Get recent SEC filings for a company or across all filers.\n\nArgs:\n    identifier: Company ticker/CIK (optional, omit for all recent filings)\n    form_type: Filter by form type (e.g., \"10-K\", \"10-Q\", \"8-K\", \"4\")\n    days: Number of days to look back (default: 30)\n    limit: Maximum filings to return (default: 50)\n\nReturns:\n    List of filings with dates, form types, accession numbers, and SEC URLs.",
    "get_recommended_tools": "Get recommended tools for analyzing a specific SEC form type.\n\nArgs:\n    form_type: SEC form type (e.g., \"10-K\", \"8-K\", \"4\", \"DEF 14A\")\n\nReturns:\n    Recommended tools and usage tips for the form type.",
    "get_segment_data": "",
    "get_xbrl_concepts": "",
    "search_companies": "Search for companies by name in SEC records.\n\nArgs:\n    query: Company name search query\n    limit: Maximum results to return (default: 10)\n\nReturns:\n    List of matching companies with CIK and ticker information."
}

TOOL_SCHEMAS: dict[str, dict] = {
    "analyze_8k": {
        "type": "object",
        "properties": {
            "identifier": {
                "type": "string"
            },
            "accession_number": {
                "type": "string"
            }
        },
        "required": [
            "identifier",
            "accession_number"
        ]
    },
    "analyze_form4_transactions": {
        "type": "object",
        "properties": {
            "identifier": {
                "type": "string"
            },
            "days": {
                "type": "string"
            },
            "limit": {
                "type": "string"
            }
        },
        "required": [
            "identifier",
            "days",
            "limit"
        ]
    },
    "analyze_insider_sentiment": {
        "type": "object",
        "properties": {
            "identifier": {
                "type": "string"
            },
            "months": {
                "type": "string"
            }
        },
        "required": [
            "identifier",
            "months"
        ]
    },
    "compare_periods": {
        "type": "object",
        "properties": {
            "identifier": {
                "type": "string"
            },
            "metric": {
                "type": "string"
            },
            "start_year": {
                "type": "string"
            },
            "end_year": {
                "type": "string"
            }
        },
        "required": [
            "identifier",
            "metric",
            "start_year",
            "end_year"
        ]
    },
    "discover_company_metrics": {
        "type": "object",
        "properties": {
            "identifier": {
                "type": "string"
            },
            "search_term": {
                "type": "string"
            }
        },
        "required": [
            "identifier",
            "search_term"
        ]
    },
    "discover_xbrl_concepts": {
        "type": "object",
        "properties": {
            "identifier": {
                "type": "string"
            },
            "accession_number": {
                "type": "string"
            },
            "form_type": {
                "type": "string"
            },
            "namespace_filter": {
                "type": "string"
            }
        },
        "required": [
            "identifier",
            "accession_number",
            "form_type",
            "namespace_filter"
        ]
    },
    "get_cik_by_ticker": {
        "type": "object",
        "properties": {
            "ticker": {
                "type": "string"
            }
        },
        "required": [
            "ticker"
        ]
    },
    "get_company_facts": {
        "type": "object",
        "properties": {
            "identifier": {
                "type": "string"
            }
        },
        "required": [
            "identifier"
        ]
    },
    "get_company_info": {
        "type": "object",
        "properties": {
            "identifier": {
                "type": "string"
            }
        },
        "required": [
            "identifier"
        ]
    },
    "get_filing_content": {
        "type": "object",
        "properties": {
            "identifier": {
                "type": "string"
            },
            "accession_number": {
                "type": "string"
            },
            "offset": {
                "type": "string"
            },
            "max_chars": {
                "type": "string"
            }
        },
        "required": [
            "identifier",
            "accession_number",
            "offset",
            "max_chars"
        ]
    },
    "get_filing_sections": {
        "type": "object",
        "properties": {
            "identifier": {
                "type": "string"
            },
            "accession_number": {
                "type": "string"
            },
            "form_type": {
                "type": "string"
            }
        },
        "required": [
            "identifier",
            "accession_number",
            "form_type"
        ]
    },
    "get_financials": {
        "type": "object",
        "properties": {
            "identifier": {
                "type": "string"
            },
            "statement_type": {
                "type": "string"
            }
        },
        "required": [
            "identifier",
            "statement_type"
        ]
    },
    "get_form4_details": {
        "type": "object",
        "properties": {
            "identifier": {
                "type": "string"
            },
            "accession_number": {
                "type": "string"
            }
        },
        "required": [
            "identifier",
            "accession_number"
        ]
    },
    "get_insider_summary": {
        "type": "object",
        "properties": {
            "identifier": {
                "type": "string"
            },
            "days": {
                "type": "string"
            }
        },
        "required": [
            "identifier",
            "days"
        ]
    },
    "get_insider_transactions": {
        "type": "object",
        "properties": {
            "identifier": {
                "type": "string"
            },
            "form_types": {
                "type": "string"
            },
            "days": {
                "type": "string"
            },
            "limit": {
                "type": "string"
            }
        },
        "required": [
            "identifier",
            "form_types",
            "days",
            "limit"
        ]
    },
    "get_key_metrics": {
        "type": "object",
        "properties": {
            "identifier": {
                "type": "string"
            },
            "metrics": {
                "type": "string"
            }
        },
        "required": [
            "identifier",
            "metrics"
        ]
    },
    "get_recent_filings": {
        "type": "object",
        "properties": {
            "identifier": {
                "type": "string"
            },
            "form_type": {
                "type": "string"
            },
            "days": {
                "type": "string"
            },
            "limit": {
                "type": "string"
            }
        },
        "required": [
            "identifier",
            "form_type",
            "days",
            "limit"
        ]
    },
    "get_recommended_tools": {
        "type": "object",
        "properties": {
            "form_type": {
                "type": "string"
            }
        },
        "required": [
            "form_type"
        ]
    },
    "get_segment_data": {
        "type": "object",
        "properties": {
            "identifier": {
                "type": "string"
            },
            "segment_type": {
                "type": "string"
            }
        },
        "required": [
            "identifier",
            "segment_type"
        ]
    },
    "get_xbrl_concepts": {
        "type": "object",
        "properties": {
            "identifier": {
                "type": "string"
            },
            "accession_number": {
                "type": "string"
            },
            "concepts": {
                "type": "string"
            },
            "form_type": {
                "type": "string"
            }
        },
        "required": [
            "identifier",
            "accession_number",
            "concepts",
            "form_type"
        ]
    },
    "search_companies": {
        "type": "object",
        "properties": {
            "query": {
                "type": "string"
            },
            "limit": {
                "type": "string"
            }
        },
        "required": [
            "query",
            "limit"
        ]
    }
}


@server.list_tools()
async def list_tools() -> list[types.Tool]:
    return [
        types.Tool(name=name, description=DOCSTRINGS[name], inputSchema=TOOL_SCHEMAS[name])
        for name in DOCSTRINGS
    ]


@server.call_tool()
async def call_tool(
    name: str, arguments: dict
) -> list[types.TextContent | types.ImageContent | types.EmbeddedResource]:
    if name not in DOCSTRINGS:
        raise ValueError(f"Unknown tool: {name}")
    return [types.TextContent(type="text", text=json.dumps({"stub": True, "tool": name, "args": arguments}))]


async def main() -> None:
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name="exp1_stefanoamorelli_sec_edgar_mcp",
                server_version="0.1.0",
                capabilities=server.get_capabilities(
                    notification_options=NotificationOptions(),
                    experimental_capabilities={},
                ),
            ),
        )


if __name__ == "__main__":
    asyncio.run(main())
