from __future__ import annotations

# EXP-1 mirror server -- LycheeMem-LycheeMem (LycheeMem/LycheeMem).
# GENERATED by scripts/exp1_generate_mirror_server.py from
# evals/fixtures/exp1_mirrors/LycheeMem-LycheeMem.json -- do not hand-edit.
#
# LOCAL MIRROR ONLY: real tool names + VERBATIM docstrings from public source.
# Generic stub body (no live APIs, no per-tool logic) -- EXP-1's regime classifier
# tests tool SELECTION only, never call-correctness.
#
# commit=3973b2f9627643615d9f222cde48f4db5d09f64a; extraction_method=regex_fallback_on_python; doc_density_composite=100.0; params are name-only placeholders (annotation='Any') -- EXP-1 classifier tests selection only, not call-correctness.

import asyncio
import json

import mcp.types as types
from mcp.server import Server
from mcp.server.lowlevel.server import NotificationOptions
from mcp.server.models import InitializationOptions
from mcp.server.stdio import stdio_server

server = Server("exp1_LycheeMem_LycheeMem")

DOCSTRINGS: dict[str, str] = {
    "lycheemem_health": "Check whether the configured LycheeMem server is reachable.",
    "lycheemem_append_turn": "Append one conversation turn into LycheeMem's session store.",
    "lycheemem_consolidate": "Persist newly appended turns into LycheeMem long-term memory.",
    "lycheemem": "Inspect LycheeMem status, recall, and consolidation from the current Hermes session."
}

TOOL_SCHEMAS: dict[str, dict] = {
    "lycheemem_health": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "lycheemem_append_turn": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "lycheemem_consolidate": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "lycheemem": {
        "type": "object",
        "properties": {},
        "required": []
    }
}


@server.list_tools()
async def list_tools() -> list[types.Tool]:
    return [
        types.Tool(name=name, description=DOCSTRINGS[name], inputSchema=TOOL_SCHEMAS[name])
        for name in DOCSTRINGS
    ]


@server.call_tool()
async def call_tool(
    name: str, arguments: dict
) -> list[types.TextContent | types.ImageContent | types.EmbeddedResource]:
    if name not in DOCSTRINGS:
        raise ValueError(f"Unknown tool: {name}")
    return [types.TextContent(type="text", text=json.dumps({"stub": True, "tool": name, "args": arguments}))]


async def main() -> None:
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name="exp1_LycheeMem_LycheeMem",
                server_version="0.1.0",
                capabilities=server.get_capabilities(
                    notification_options=NotificationOptions(),
                    experimental_capabilities={},
                ),
            ),
        )


if __name__ == "__main__":
    asyncio.run(main())
