from __future__ import annotations

# EXP-1 mirror server -- stickerdaniel-linkedin-mcp-server (stickerdaniel/linkedin-mcp-server).
# GENERATED by scripts/exp1_generate_mirror_server.py from
# evals/fixtures/exp1_mirrors/stickerdaniel-linkedin-mcp-server.json -- do not hand-edit.
#
# LOCAL MIRROR ONLY: real tool names + VERBATIM docstrings from public source.
# Generic stub body (no live APIs, no per-tool logic) -- EXP-1's regime classifier
# tests tool SELECTION only, never call-correctness.
#
# commit=a8ca5df79ded1b454bf734f010485c815a6b315a; extraction_method=ast; doc_density_composite=94.2; params are name-only placeholders (annotation='Any') -- EXP-1 classifier tests selection only, not call-correctness.

import asyncio
import json

import mcp.types as types
from mcp.server import Server
from mcp.server.lowlevel.server import NotificationOptions
from mcp.server.models import InitializationOptions
from mcp.server.stdio import stdio_server

server = Server("exp1_stickerdaniel_linkedin_mcp_server")

DOCSTRINGS: dict[str, str] = {
    "close_session": "Close the current browser session and clean up resources.",
    "get_company_profile": "Get a specific company's LinkedIn profile.\n\nArgs:\n    company_name: LinkedIn company name (e.g., \"docker\", \"anthropic\", \"microsoft\")\n    ctx: FastMCP context for progress reporting\n    sections: Comma-separated list of extra sections to scrape.\n        The about page is always included.\n        Available sections: posts, jobs\n        Examples: \"posts\", \"posts,jobs\"\n        Default (None) scrapes only the about page.\n\nReturns:\n    Dict with url, sections (name -> raw text), and optional references.\n    Includes unknown_sections list when unrecognised names are passed.\n    The LLM should parse the raw text in each section.\n\n    When the about section is included, references[\"about\"] may\n    include a {kind: \"company_urn\", value: \"<numeric-id>\"} entry —\n    present whenever the page exposes the \"See all employees\" link\n    (typically all but the smallest companies). The value is the\n    numeric id LinkedIn's people-search uses in its currentCompany\n    URL facet; plain-text company names are silently ignored by\n    that facet.",
    "get_company_posts": "Get recent posts from a company's LinkedIn feed.\n\nArgs:\n    company_name: LinkedIn company name (e.g., \"docker\", \"anthropic\", \"microsoft\")\n    ctx: FastMCP context for progress reporting\n\nReturns:\n    Dict with url, sections (name -> raw text), and optional references.\n    The LLM should parse the raw text to extract individual posts.",
    "search_companies": "Search for companies on LinkedIn.\n\nArgs:\n    keywords: Search keywords (e.g., \"fintech\", \"anthropic\", \"electric vehicles\")\n    ctx: FastMCP context for progress reporting\n\nReturns:\n    Dict with url, sections (search_results -> raw text), and optional references.\n    The LLM should parse the raw text to extract individual companies and their pages.",
    "get_company_employees": "List employees at a company from the LinkedIn /people/ page, including\nthe demographics aggregate that this view exposes: where employees\nlive, where they studied, and a function breakdown (Engineering, Sales,\nOperations, etc.). The demographics are unique to this tool.\n\nFor filtered search by network degree (1st/2nd/3rd) or location, prefer\nsearch_people with current_company set to the company URN id. That path\nalso returns more result pages than the /people/ tab.\n\nThe optional keywords filter narrows results by name, title, or skill.\n\ncompany_name must be the exact LinkedIn URL slug (the path segment after\n/company/), not the display name. LinkedIn assigns unique slugs and the\ndisplay name often does not match. For example, the AI lab Anthropic\nlives at /company/anthropicresearch/, not /company/anthropic/. If you\nare unsure of the slug, call search_companies first and pick the slug\nfrom the returned references.\n\nArgs:\n    company_name: LinkedIn company URL slug (e.g., \"docker\", \"anthropicresearch\", \"microsoft\")\n    ctx: FastMCP context for progress reporting\n    keywords: Optional filter by name, job title, or skill (e.g., \"engineer\", \"sales\")\n\nReturns:\n    Dict with url, sections (employees -> raw text), and optional references.\n    References include /in/ profile paths for listed employees.",
    "get_feed": "Get posts from the authenticated user's LinkedIn feed.\n\nArgs:\n    ctx: FastMCP context for progress reporting\n    num_posts: Number of posts to fetch (1-50, default 10).\n               Posts are loaded in batches of ~5 as the page scrolls,\n               so the actual count may slightly exceed the target.\n\nReturns:\n    Dict with url, sections (name -> raw text), and optional keys:\n    - references[\"feed\"]: list of {kind: \"feed_post\", url, ...}\n      entries. URLs are relative paths and may carry either\n      ``/feed/update/<urn>/`` (DOM-anchor-derived) or\n      ``/posts/<slug>`` (SDUI-derived) shape — both are valid\n      LinkedIn permalinks.\n    - section_errors: present when the feed is rate-limited or\n      extraction fails.\n\n    Truncated posts are not auto-expanded; full text for any post\n    is reachable via its permalink in references[\"feed\"]. The LLM\n    should parse sections[\"feed\"] for post bodies.",
    "get_job_details": "Get job details for a specific job posting on LinkedIn.\n\nArgs:\n    job_id: LinkedIn job ID (e.g., \"4252026496\", \"3856789012\")\n    ctx: FastMCP context for progress reporting\n\nReturns:\n    Dict with url, sections (name -> raw text), and optional references.\n    The LLM should parse the raw text to extract job details.",
    "search_jobs": "Search for jobs on LinkedIn.\n\nReturns job_ids that can be passed to get_job_details for full info.\n\nArgs:\n    keywords: Search keywords (e.g., \"software engineer\", \"data scientist\")\n    ctx: FastMCP context for progress reporting\n    location: Optional location filter (e.g., \"San Francisco\", \"Remote\")\n    max_pages: Maximum number of result pages to load (1-10, default 3)\n    date_posted: Filter by posting date (past_hour, past_24_hours, past_week, past_month)\n    job_type: Filter by job type, comma-separated (full_time, part_time, contract, temporary, volunteer, internship, other)\n    experience_level: Filter by experience level, comma-separated (internship, entry, associate, mid_senior, director, executive)\n    work_type: Filter by work type, comma-separated (on_site, remote, hybrid)\n    easy_apply: Only show Easy Apply jobs (default false)\n    sort_by: Sort results (date, relevance)\n\nReturns:\n    Dict with url, sections (name -> raw text), job_ids (list of\n    numeric job ID strings usable with get_job_details), and optional references.",
    "get_inbox": "List recent conversations from the LinkedIn messaging inbox.\n\nArgs:\n    ctx: FastMCP context for progress reporting\n    limit: Maximum number of conversations to load (1-50, default 20)\n\nReturns:\n    Dict with url, sections (inbox -> raw text), and optional references.",
    "get_conversation": "Read a specific messaging conversation.\n\nProvide either linkedin_username or thread_id to identify the conversation.\n\nWhen looked up by linkedin_username, resolution searches the messaging\ninbox for the participant's display name and click-visits every\nmatching row to capture its thread ID — LinkedIn's sidebar has no\nanchor hrefs or thread-id attributes, so this is the only available\npath. Each visit selects the row in the LinkedIn UI and may mark it\nas read. Pass thread_id directly to skip this enumeration.\n\nArgs:\n    ctx: FastMCP context for progress reporting\n    linkedin_username: LinkedIn username of the conversation participant\n    thread_id: LinkedIn messaging thread ID\n    index: 0-based selector for which thread to open when the\n        participant has multiple threads (e.g. an organic 1-on-1 plus\n        an InMail). Ignored when thread_id is provided. To enumerate\n        thread IDs first, call search_conversations.\n\nReturns:\n    Dict with url, sections (conversation -> raw text), and optional references.",
    "search_conversations": "Search messages by keyword.\n\nArgs:\n    keywords: Search keywords to filter conversations\n    ctx: FastMCP context for progress reporting\n    limit: Maximum number of search-result rows to enumerate as\n        conversation references (1-50, default 20). Each enumeration\n        selects the row in LinkedIn's UI and may mark it as read, so\n        a low cap is preferable for noisy queries.\n\nReturns:\n    Dict with url, sections (search_results -> raw text), and optional references.",
    "send_message": "Send a message to a LinkedIn user.\n\nThe recipient must be directly messageable from the profile page. This is a\nwrite operation when confirm_send is True.\n\nArgs:\n    linkedin_username: LinkedIn username of the recipient\n    message: The message text to send\n    confirm_send: Must be True to send the message\n    ctx: FastMCP context for progress reporting\n    profile_urn: Optional profile URN (e.g. ACoAAB...) to construct the\n        compose URL directly. Providing this bypasses the Message-button\n        lookup and is more reliable when available. Obtain via\n        get_person_profile. Note: inbox may not always show all\n        messages; use search_conversations as a fallback.\n\nReturns:\n    Dict with url, status, message, recipient_selected, and sent.",
    "get_person_profile": "Get a specific person's LinkedIn profile.\n\nArgs:\n    linkedin_username: LinkedIn username (e.g., \"stickerdaniel\", \"williamhgates\")\n    ctx: FastMCP context for progress reporting\n    sections: Comma-separated list of extra sections to scrape.\n        The main profile page is always included.\n        Available sections: experience, education, interests, honors, languages, certifications, skills, projects, contact_info, posts\n        Examples: \"experience,education\", \"contact_info\", \"skills,projects\", \"honors,languages\", \"posts\"\n        Default (None) scrapes only the main profile page.\n    max_scrolls: Maximum pagination attempts per section to load more content.\n        On detail sections (experience, certifications, skills, etc.) this\n        is the max number of \"Show more\" button clicks. On activity/posts\n        it is the max scroll-to-bottom iterations. Applies to all sections\n        in this call. Default (None) uses 5 for detail sections and 10 for\n        posts. Increase when a profile has many items in a section\n        (e.g., 30+ certifications, max_scrolls=20). To avoid slowing down\n        other sections, request heavy sections in a separate call.\n\nReturns:\n    Dict with url, sections (name -> raw text), and optional references.\n    Sections may be absent if extraction yielded no content for that page.\n    Includes unknown_sections list when unrecognised names are passed.\n    The LLM should parse the raw text in each section.",
    "search_people": "Search for people on LinkedIn.\n\nArgs:\n    keywords: Search keywords (e.g., \"software engineer\", \"recruiter at Google\")\n    ctx: FastMCP context for progress reporting\n    location: Optional location filter (e.g., \"New York\", \"Remote\")\n    network: Optional connection-degree filter. Each element is one of\n        \"F\" (1st-degree), \"S\" (2nd-degree), \"O\" (3rd-degree and beyond).\n        Example: [\"F\"] to only return 1st-degree connections.\n    current_company: Optional current-employer filter. LinkedIn's\n        currentCompany facet only filters on the numeric company URN id\n        (e.g. \"1115\" for SAP); plain company names are accepted by the\n        URL but ignored by LinkedIn and return the unfiltered result\n        set. Look up a company's URN via get_company_profile -- it is\n        exposed under references[\"about\"]. For company-wide employee\n        demographics (location/education/function breakdown) plus a\n        slug-based lookup, use get_company_employees instead.\n\nReturns:\n    Dict with url, sections (name -> raw text), and optional references.\n    The LLM should parse the raw text to extract individual people and their profiles.",
    "connect_with_person": "Send a LinkedIn connection request or accept an incoming one.\n\nThe tool is annotated with destructiveHint so MCP clients will\nprompt for user confirmation before execution.\n\nArgs:\n    linkedin_username: LinkedIn username (e.g., \"stickerdaniel\", \"williamhgates\")\n    ctx: FastMCP context for progress reporting\n    note: Optional note to include with the invitation\n\nReturns:\n    Dict with url, status, message, and note_sent.\n    Statuses: pending, already_connected, follow_only,\n    connect_unavailable, unavailable, send_failed,\n    note_not_supported, custom_note_limit_reached,\n    connected, or accepted.\n\n    When status is ``custom_note_limit_reached`` LinkedIn rejected\n    personalized invite notes because the free note quota for the\n    account is exhausted. The ``message`` is the raw Premium dialog\n    text read from LinkedIn.",
    "get_sidebar_profiles": "Get profile links from sidebar recommendation sections on a LinkedIn profile page.\n\nExtracts profiles from \"More profiles for you\", \"Explore premium profiles\",\nand \"People you may know\" sidebar sections. Follows \"Show all\" links to\nreturn the full list from each section. Sections that redirect to\nlinkedin.com/premium are skipped.\n\nArgs:\n    linkedin_username: LinkedIn username of the profile page to scrape\n        (e.g., \"stickerdaniel\", \"williamhgates\")\n    ctx: FastMCP context for progress reporting\n\nReturns:\n    Dict with url and sidebar_profiles mapping section key to a list of\n    /in/username/ paths. Only sections present on the page are included.",
    "get_my_profile": "Get the authenticated user's own LinkedIn profile.\n\nNavigates to /in/me/ and resolves the redirect to obtain the real\nusername before scraping, so the url field in the result is the actual\nprofile URL (e.g. linkedin.com/in/johndoe/) rather than /in/me/.\n\nArgs:\n    ctx: FastMCP context for progress reporting\n    sections: Comma-separated list of extra sections to scrape.\n        The main profile page is always included.\n        Available sections: experience, education, interests, honors, languages, certifications, skills, projects, contact_info, posts\n        Examples: \"experience,education\", \"contact_info\", \"skills,projects\"\n        Default (None) scrapes only the main profile page.\n    max_scrolls: Maximum pagination attempts per section (same as get_person_profile).\n\nReturns:\n    Dict with url, sections (name -> raw text), and optional references.\n    The url field reflects the resolved profile URL, revealing the real username."
}

TOOL_SCHEMAS: dict[str, dict] = {
    "close_session": {
        "type": "object",
        "properties": {},
        "required": []
    },
    "get_company_profile": {
        "type": "object",
        "properties": {
            "company_name": {
                "type": "string"
            },
            "sections": {
                "type": "string"
            },
            "extractor": {
                "type": "string"
            }
        },
        "required": [
            "company_name",
            "sections",
            "extractor"
        ]
    },
    "get_company_posts": {
        "type": "object",
        "properties": {
            "company_name": {
                "type": "string"
            },
            "extractor": {
                "type": "string"
            }
        },
        "required": [
            "company_name",
            "extractor"
        ]
    },
    "search_companies": {
        "type": "object",
        "properties": {
            "keywords": {
                "type": "string"
            },
            "extractor": {
                "type": "string"
            }
        },
        "required": [
            "keywords",
            "extractor"
        ]
    },
    "get_company_employees": {
        "type": "object",
        "properties": {
            "company_name": {
                "type": "string"
            },
            "keywords": {
                "type": "string"
            },
            "extractor": {
                "type": "string"
            }
        },
        "required": [
            "company_name",
            "keywords",
            "extractor"
        ]
    },
    "get_feed": {
        "type": "object",
        "properties": {
            "num_posts": {
                "type": "string"
            },
            "extractor": {
                "type": "string"
            }
        },
        "required": [
            "num_posts",
            "extractor"
        ]
    },
    "get_job_details": {
        "type": "object",
        "properties": {
            "job_id": {
                "type": "string"
            },
            "extractor": {
                "type": "string"
            }
        },
        "required": [
            "job_id",
            "extractor"
        ]
    },
    "search_jobs": {
        "type": "object",
        "properties": {
            "keywords": {
                "type": "string"
            },
            "location": {
                "type": "string"
            },
            "max_pages": {
                "type": "string"
            },
            "date_posted": {
                "type": "string"
            },
            "job_type": {
                "type": "string"
            },
            "experience_level": {
                "type": "string"
            },
            "work_type": {
                "type": "string"
            },
            "easy_apply": {
                "type": "string"
            },
            "sort_by": {
                "type": "string"
            },
            "extractor": {
                "type": "string"
            }
        },
        "required": [
            "keywords",
            "location",
            "max_pages",
            "date_posted",
            "job_type",
            "experience_level",
            "work_type",
            "easy_apply",
            "sort_by",
            "extractor"
        ]
    },
    "get_inbox": {
        "type": "object",
        "properties": {
            "limit": {
                "type": "string"
            },
            "extractor": {
                "type": "string"
            }
        },
        "required": [
            "limit",
            "extractor"
        ]
    },
    "get_conversation": {
        "type": "object",
        "properties": {
            "linkedin_username": {
                "type": "string"
            },
            "thread_id": {
                "type": "string"
            },
            "index": {
                "type": "string"
            },
            "extractor": {
                "type": "string"
            }
        },
        "required": [
            "linkedin_username",
            "thread_id",
            "index",
            "extractor"
        ]
    },
    "search_conversations": {
        "type": "object",
        "properties": {
            "keywords": {
                "type": "string"
            },
            "limit": {
                "type": "string"
            },
            "extractor": {
                "type": "string"
            }
        },
        "required": [
            "keywords",
            "limit",
            "extractor"
        ]
    },
    "send_message": {
        "type": "object",
        "properties": {
            "linkedin_username": {
                "type": "string"
            },
            "message": {
                "type": "string"
            },
            "confirm_send": {
                "type": "string"
            },
            "profile_urn": {
                "type": "string"
            },
            "extractor": {
                "type": "string"
            }
        },
        "required": [
            "linkedin_username",
            "message",
            "confirm_send",
            "profile_urn",
            "extractor"
        ]
    },
    "get_person_profile": {
        "type": "object",
        "properties": {
            "linkedin_username": {
                "type": "string"
            },
            "sections": {
                "type": "string"
            },
            "max_scrolls": {
                "type": "string"
            },
            "extractor": {
                "type": "string"
            }
        },
        "required": [
            "linkedin_username",
            "sections",
            "max_scrolls",
            "extractor"
        ]
    },
    "search_people": {
        "type": "object",
        "properties": {
            "keywords": {
                "type": "string"
            },
            "location": {
                "type": "string"
            },
            "network": {
                "type": "string"
            },
            "current_company": {
                "type": "string"
            },
            "extractor": {
                "type": "string"
            }
        },
        "required": [
            "keywords",
            "location",
            "network",
            "current_company",
            "extractor"
        ]
    },
    "connect_with_person": {
        "type": "object",
        "properties": {
            "linkedin_username": {
                "type": "string"
            },
            "note": {
                "type": "string"
            },
            "extractor": {
                "type": "string"
            }
        },
        "required": [
            "linkedin_username",
            "note",
            "extractor"
        ]
    },
    "get_sidebar_profiles": {
        "type": "object",
        "properties": {
            "linkedin_username": {
                "type": "string"
            },
            "extractor": {
                "type": "string"
            }
        },
        "required": [
            "linkedin_username",
            "extractor"
        ]
    },
    "get_my_profile": {
        "type": "object",
        "properties": {
            "sections": {
                "type": "string"
            },
            "max_scrolls": {
                "type": "string"
            },
            "extractor": {
                "type": "string"
            }
        },
        "required": [
            "sections",
            "max_scrolls",
            "extractor"
        ]
    }
}


@server.list_tools()
async def list_tools() -> list[types.Tool]:
    return [
        types.Tool(name=name, description=DOCSTRINGS[name], inputSchema=TOOL_SCHEMAS[name])
        for name in DOCSTRINGS
    ]


@server.call_tool()
async def call_tool(
    name: str, arguments: dict
) -> list[types.TextContent | types.ImageContent | types.EmbeddedResource]:
    if name not in DOCSTRINGS:
        raise ValueError(f"Unknown tool: {name}")
    return [types.TextContent(type="text", text=json.dumps({"stub": True, "tool": name, "args": arguments}))]


async def main() -> None:
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name="exp1_stickerdaniel_linkedin_mcp_server",
                server_version="0.1.0",
                capabilities=server.get_capabilities(
                    notification_options=NotificationOptions(),
                    experimental_capabilities={},
                ),
            ),
        )


if __name__ == "__main__":
    asyncio.run(main())
