from __future__ import annotations

# P2-A experiment — Arm GuardB (Guard-B descriptions generated from mirror docstrings).
#
# Descriptions generated by qwen3:8b using scoped extraction from p2a_internal_proxy_mirror.py
# with Guard B: only target-grounded positive facts, no comparative neighbor claims.
# Generated by scripts/p2a_phase1_generate.py; persisted to the JSON file below.
# Falls back to ARM_A_DESCRIPTIONS (thin baseline) if the JSON does not exist yet.
# Only contested tools receive generated descriptions; thorough tools use ARM_A as-is.

import asyncio
import json

import mcp.types as types
from mcp.server import Server
from mcp.server.lowlevel.server import NotificationOptions
from mcp.server.models import InitializationOptions
from mcp.server.stdio import stdio_server

from evals.fixtures.p2a_internal_proxy_catalog import ARM_A_DESCRIPTIONS, TOOL_SCHEMAS

_ARM_PATH = (
    __import__("pathlib").Path(__file__).parent.parent
    / "evals"
    / "fixtures"
    / "p2a_arm_guardb_descriptions.json"
)

if _ARM_PATH.exists():
    _ARM_DESCS: dict[str, str] = json.loads(_ARM_PATH.read_text(encoding="utf-8"))
else:
    # Phase 1 not yet run; fall back to thin one-liner baseline
    _ARM_DESCS = dict(ARM_A_DESCRIPTIONS)

server = Server("p2a-arm-guardb")


@server.list_tools()
async def list_tools() -> list[types.Tool]:
    return [
        types.Tool(
            name=name,
            description=_ARM_DESCS.get(name, ARM_A_DESCRIPTIONS[name]),
            inputSchema=schema,
        )
        for name, schema in TOOL_SCHEMAS.items()
    ]


@server.call_tool()
async def call_tool(
    name: str, arguments: dict
) -> list[types.TextContent | types.ImageContent | types.EmbeddedResource]:
    result = json.dumps({"tool": name, "args": sorted(arguments.keys())})
    return [types.TextContent(type="text", text=result)]


async def main() -> None:
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name="p2a-arm-guardb",
                server_version="0.1.0",
                capabilities=server.get_capabilities(
                    notification_options=NotificationOptions(),
                    experimental_capabilities={},
                ),
            ),
        )


if __name__ == "__main__":
    asyncio.run(main())
