from __future__ import annotations

# Q4 scoped-source experiment — Arm F-DOC-scoped.
# Descriptions generated by qwen3:8b using scoped source (target function only + neighbor surfaces)
# with the DOC variant (docstrings present).
# Falls back to empty string if the JSON file has not been generated yet.

import asyncio
import json

import mcp.types as types
from mcp.server import Server
from mcp.server.lowlevel.server import NotificationOptions
from mcp.server.models import InitializationOptions
from mcp.server.stdio import stdio_server

from evals.fixtures.q3_catalog import FAMILIES

_ARM_PATH = (
    __import__("pathlib").Path(__file__).parent.parent
    / "evals"
    / "fixtures"
    / "q4_arm_f_doc_scoped_descriptions.json"
)

if _ARM_PATH.exists():
    _ARM_DESCS: dict[str, str] = json.loads(_ARM_PATH.read_text(encoding="utf-8"))
else:
    _ARM_DESCS = {}

server = Server("q4-arm-f-doc-scoped")

_SCHEMA = {"type": "object", "properties": {"query": {"type": "string"}}, "required": ["query"]}


@server.list_tools()
async def list_tools() -> list[types.Tool]:
    return [
        types.Tool(name=name, description=_ARM_DESCS.get(name, ""), inputSchema=_SCHEMA)
        for names in FAMILIES.values()
        for name in names
    ]


@server.call_tool()
async def call_tool(
    name: str, arguments: dict
) -> list[types.TextContent | types.ImageContent | types.EmbeddedResource]:
    result = json.dumps({"tool": name, "query": arguments.get("query", "")})
    return [types.TextContent(type="text", text=result)]


async def main() -> None:
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name="q4-arm-f-doc-scoped",
                server_version="0.1.0",
                capabilities=server.get_capabilities(
                    notification_options=NotificationOptions(),
                    experimental_capabilities={},
                ),
            ),
        )


if __name__ == "__main__":
    asyncio.run(main())
