from __future__ import annotations

# T18 discoverability-at-scale fixture — Arm F (fixer-generated descriptions).
#
# 60 tools in 10 families. Arm F descriptions are generated by the current fixer
# (per-tool generator prompt, qwen3:8b) and persisted to
# evals/fixtures/t18_arm_f_descriptions.json by scripts/generate_arm_f_descriptions.py.
# Tools with no entry in the file fall back to empty descriptions (same as Arm A).
import asyncio
import json

import mcp.types as types
from mcp.server import Server
from mcp.server.lowlevel.server import NotificationOptions
from mcp.server.models import InitializationOptions
from mcp.server.stdio import stdio_server

from agentgauge.q2a_harness import load_arm_f_descriptions
from evals.fixtures.t18_catalog import FAMILIES

ARM_F_DESCRIPTIONS = load_arm_f_descriptions()

server = Server("t18-discoverability-arm-f")

_SCHEMA = {"type": "object", "properties": {"query": {"type": "string"}}, "required": ["query"]}


@server.list_tools()
async def list_tools() -> list[types.Tool]:
    """Return all 60 tools with fixer-generated descriptions (Arm F)."""
    tools: list[types.Tool] = []
    for _family, tool_names in FAMILIES.items():
        for name in tool_names:
            tools.append(
                types.Tool(
                    name=name,
                    description=ARM_F_DESCRIPTIONS.get(name, ""),
                    inputSchema=_SCHEMA,
                )
            )
    return tools


@server.call_tool()
async def call_tool(
    name: str, arguments: dict
) -> list[types.TextContent | types.ImageContent | types.EmbeddedResource]:
    result = json.dumps({"tool": name, "query": arguments.get("query", "")})
    return [types.TextContent(type="text", text=result)]


async def main() -> None:
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name="t18-discoverability-arm-f",
                server_version="0.1.0",
                capabilities=server.get_capabilities(
                    notification_options=NotificationOptions(),
                    experimental_capabilities={},
                ),
            ),
        )


if __name__ == "__main__":
    asyncio.run(main())
