from __future__ import annotations

# T18 discoverability-at-scale fixture — Arm F Q2b (catalog-aware fixer descriptions).
#
# 60 tools in 10 families. Arm F Q2b descriptions are generated by the catalog-aware
# fixer (qwen3:8b with neighbor context) and persisted to
# evals/fixtures/t18_arm_f_q2b_descriptions.json by
# scripts/generate_arm_f_descriptions_q2b.py.
# Tools with no entry fall back to empty descriptions (same as Arm A).
import asyncio
import json

import mcp.types as types
from mcp.server import Server
from mcp.server.lowlevel.server import NotificationOptions
from mcp.server.models import InitializationOptions
from mcp.server.stdio import stdio_server

from evals.fixtures.t18_catalog import FAMILIES

_ARM_F_Q2B_PATH = (
    __import__("pathlib").Path(__file__).parent.parent
    / "evals"
    / "fixtures"
    / "t18_arm_f_q2b_descriptions.json"
)

if _ARM_F_Q2B_PATH.exists():
    ARM_F_Q2B_DESCRIPTIONS: dict[str, str] = json.loads(
        _ARM_F_Q2B_PATH.read_text(encoding="utf-8")
    )
else:
    ARM_F_Q2B_DESCRIPTIONS = {}

server = Server("t18-discoverability-arm-f-q2b")

_SCHEMA = {"type": "object", "properties": {"query": {"type": "string"}}, "required": ["query"]}


@server.list_tools()
async def list_tools() -> list[types.Tool]:
    """Return all 60 tools with Q2b catalog-aware fixer descriptions (Arm F Q2b)."""
    tools: list[types.Tool] = []
    for _family, tool_names in FAMILIES.items():
        for name in tool_names:
            tools.append(
                types.Tool(
                    name=name,
                    description=ARM_F_Q2B_DESCRIPTIONS.get(name, ""),
                    inputSchema=_SCHEMA,
                )
            )
    return tools


@server.call_tool()
async def call_tool(
    name: str, arguments: dict
) -> list[types.TextContent | types.ImageContent | types.EmbeddedResource]:
    result = json.dumps({"tool": name, "query": arguments.get("query", "")})
    return [types.TextContent(type="text", text=result)]


async def main() -> None:
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name="t18-discoverability-arm-f-q2b",
                server_version="0.1.0",
                capabilities=server.get_capabilities(
                    notification_options=NotificationOptions(),
                    experimental_capabilities={},
                ),
            ),
        )


if __name__ == "__main__":
    asyncio.run(main())
