from __future__ import annotations

# EXP-1 STEP 1 (mirroring) -- generates a RUNNABLE Python MCP stub server directly
# from an already-built ServerMirror JSON fixture (evals/fixtures/exp1_mirrors/*.json).
# Deterministic, no LLM/agent calls.
#
# Follows the same low-level MCP SDK boilerplate as examples/rw1_github_mirror.py
# (@server.list_tools() / @server.call_tool() over stdio), but GENERICALLY driven by
# the mirror's tool list rather than hand-authored per-tool functions -- EXP-1's
# regime classifier tests only tool SELECTION (task -> tool), never call-correctness,
# so a single generic stub body (returns {"stub": True, "tool": name, "args": ...})
# is sufficient; per-tool hand-authored bodies (RW1/RW2's style) are not needed here.
#
# Tool descriptions are asserted verbatim against the mirror JSON at generation time
# (the independence rule) -- this script does not paraphrase or edit any docstring.
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from agentgauge.exp1_mirror import ServerMirror, load_mirror  # noqa: E402

REPO_ROOT = Path(__file__).parent.parent
MIRRORS_DIR = REPO_ROOT / "evals" / "fixtures" / "exp1_mirrors"
EXAMPLES_DIR = REPO_ROOT / "examples"

_PY_TYPE_TO_JSON_SCHEMA_TYPE = {
    "str": "string",
    "int": "integer",
    "float": "number",
    "bool": "boolean",
    "list": "array",
    "dict": "object",
}


def _json_schema_type(annotation: str) -> str:
    base = annotation.split("[")[0].strip()
    return _PY_TYPE_TO_JSON_SCHEMA_TYPE.get(base, "string")


def _build_input_schema(mirror: ServerMirror) -> dict[str, dict]:
    schemas: dict[str, dict] = {}
    for tool in mirror.tools:
        properties = {p.name: {"type": _json_schema_type(p.annotation)} for p in tool.params}
        required = [p.name for p in tool.params if p.default is None]
        schemas[tool.name] = {
            "type": "object",
            "properties": properties,
            "required": required,
        }
    return schemas


def generate_server_source(mirror: ServerMirror) -> str:
    docstrings_dict = {t.name: t.docstring for t in mirror.tools}
    schemas_dict = _build_input_schema(mirror)
    module_name = f"exp1_{mirror.server_id.replace('-', '_')}"

    docstrings_literal = json.dumps(docstrings_dict, indent=4, ensure_ascii=False)
    schemas_literal = json.dumps(schemas_dict, indent=4, ensure_ascii=False)

    return f'''from __future__ import annotations

# EXP-1 mirror server -- {mirror.server_id} ({mirror.source_repo}).
# GENERATED by scripts/exp1_generate_mirror_server.py from
# evals/fixtures/exp1_mirrors/{mirror.server_id}.json -- do not hand-edit.
#
# LOCAL MIRROR ONLY: real tool names + VERBATIM docstrings from public source.
# Generic stub body (no live APIs, no per-tool logic) -- EXP-1's regime classifier
# tests tool SELECTION only, never call-correctness.
#
# {mirror.notes}

import asyncio
import json

import mcp.types as types
from mcp.server import Server
from mcp.server.lowlevel.server import NotificationOptions
from mcp.server.models import InitializationOptions
from mcp.server.stdio import stdio_server

server = Server("{module_name}")

DOCSTRINGS: dict[str, str] = {docstrings_literal}

TOOL_SCHEMAS: dict[str, dict] = {schemas_literal}


@server.list_tools()
async def list_tools() -> list[types.Tool]:
    return [
        types.Tool(name=name, description=DOCSTRINGS[name], inputSchema=TOOL_SCHEMAS[name])
        for name in DOCSTRINGS
    ]


@server.call_tool()
async def call_tool(
    name: str, arguments: dict
) -> list[types.TextContent | types.ImageContent | types.EmbeddedResource]:
    if name not in DOCSTRINGS:
        raise ValueError(f"Unknown tool: {{name}}")
    return [types.TextContent(type="text", text=json.dumps({{"stub": True, "tool": name, "args": arguments}}))]


async def main() -> None:
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name="{module_name}",
                server_version="0.1.0",
                capabilities=server.get_capabilities(
                    notification_options=NotificationOptions(),
                    experimental_capabilities={{}},
                ),
            ),
        )


if __name__ == "__main__":
    asyncio.run(main())
'''


def assert_docstrings_verbatim_in_source(mirror: ServerMirror, source: str) -> list[str]:
    """Independence check: every tool's docstring must appear verbatim (via its
    json.dumps encoding) in the generated source -- catches accidental mutation."""
    violations = []
    docstrings_literal = json.dumps(
        {t.name: t.docstring for t in mirror.tools}, indent=4, ensure_ascii=False
    )
    if docstrings_literal not in source:
        violations.append("DOCSTRINGS literal does not match mirror verbatim")
    return violations


def main() -> None:
    if len(sys.argv) != 2:
        print("Usage: exp1_generate_mirror_server.py <server_id>")
        sys.exit(1)
    server_id = sys.argv[1]
    mirror = load_mirror(MIRRORS_DIR / f"{server_id}.json")
    source = generate_server_source(mirror)

    violations = assert_docstrings_verbatim_in_source(mirror, source)
    if violations:
        print("VERBATIM ASSERTION FAILED:", violations)
        sys.exit(1)

    out_path = EXAMPLES_DIR / f"exp1_{server_id.replace('-', '_')}_mirror.py"
    out_path.write_text(source, encoding="utf-8")
    print(f"Generated {out_path} ({len(mirror.tools)} tools, verbatim-asserted)")


if __name__ == "__main__":
    main()
